- config/server.config.js
When attempting to create a vagrant box for the project (something we do across all our projects) we hit a snag. All requests to the API from the host on `http://localhost:3003` were returning `Recv failure: Connection reset by peer`.
After some investigation we found it was because we are setting `host` to `localhost` in the server config. When run directly on the host this is fine. But when run in the vagrantbox this is caused port forwarding to break.
After double checking the existing charging-module-api we confirmed `host` never gets set. So we removed it and found both local and running in the vagrantbox started working with us being able to connect to the API in both cases at `http://localhost:3003`.
> Remove `host` from server.config.js

- app/plugins/disinfect.plugin.js
- package-lock.json
- package.json
- server.js
https://trello.com/c/cjqqnLGs
During PEN testing of the [charging-module-api](https://github.com/DEFRA/charging-mdoule-api) it was found that the project is susceptible to XSS. This was because inputs to the API were not properly being sanitized. Rather than roll our own santizer, we're opting to use a plugin on this project.
[Disinfect](https://github.com/genediazjr/disinfect) has been used on a number of Defra projects. It applies Google's [Caja](https://github.com/google/caja) HTML Sanitizer on route query, payload, and params.
This change adds it to this project.
> Add disinfect plugin to santize inputs to the API

- app/plugins/blipp.plugin.js
We use the [blipp](https://github.com/danielb2/blipp) to display our routes when the service starts up. As we are now using [Route scopes](https://hapi.dev/api/?v=20.0.0#-routeoptionsauthaccessscope) as part of our authorisation solution being able to see the scopes in the Blipp output will be handy.
This change enables the scope output and expands the current documentation for the plugin.
> Enable  show scope option in Blipp plugin

- .env.example
- .travis.yml
- app/controllers/airbrake.controller.js
- app/plugins/airbrake.plugin.js
- app/plugins/router.plugin.js
- app/routes/airbrake.routes.js
- config/airbrake.config.js
- package-lock.json
- package.json
- server.js
- test/README.md
- test/controllers/airbrake.controller.test.js
- test/support/helpers/authorisation.helper.js
It's a standard across Defra projects to use the relevant [Airbrake package](https://www.npmjs.com/package/@airbrake/node) to capture errors within our apps and automatically record them in an instance of [Errbit](https://github.com/errbit/errbit) we maintain. Doing so means teams can monitor and track issues in our apps without resorting to scanning logs for issues or waiting for calls from users.
This project is no exception. So this change adds support for Airbrake.
> Add Airbrake error logging to the project

- app/models/charge.model.js
- test/models/charge.model.test.js
- test/support/fixtures/charge.json
The next step in setting up our rules service functionality is to create a Charge model. Once this is in place we can create a translator to translate incoming data to it, and a presenter to present outgoing data from it.
> Create Charge model

- .env.example
- app/auth/jwt_strategy.auth.js
- config/authentication.config.js
- test/controllers/admin/health/airbrake.controller.test.js
- test/features/authentication.test.js
- test/features/authorisation.test.js
- test/support/helpers/authorisation.helper.js
- test/support/helpers/authorised_system.helper.js
- test/support/helpers/client.helper.js
- test/support/helpers/database.helper.js
- test/support/helpers/index.js
- test/support/helpers/route.helper.js
All JWT tokens have an expiry value. [Until recently](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-cognito-user-pools-supports-customization-of-token-expiration/) those generated by AWS Cognito all had an expiry of 1 hour.
The idea is tor protect against leaked tokens. Should one become compromised you want to limit how long it has access before it is required to refresh.
In the current [charging-module-api](https://github.com/defra/charging-module-api) we just decode the token. In this project at least we are verifying it. But we are still ignoring the expiry value.
This change will close that final security hole and update our auth strategy config to include checking the expiry value of tokens. To keep local development tolerable though we'll drive it through configuration. …
> Enable JWT token expiry checking

- .travis.yml
The [Hapi Lab](https://github.com/hapijs/lab) test framework comes with the ability to run specific tests by adding `.only` to the describe block. For example
```javascript
describe.only('Sanitizing requests to the API', () => {
// ...
})
```
This is great! Just don't forget to leave them in when pushing your commits to GitHub. Having not learnt my lesson, this adds a check for use of this to the Travis build.
> Add check for use of `only()` in tests to travis

- app/plugins/index.js
- app/plugins/unescape.plugin.js
- server.js
- test/features/sanitise_payloads.test.js
- test/support/helpers/route.helper.js
https://trello.com/c/cjqqnLGs
https://github.com/DEFRA/sroc-charging-module-api/pull/4
We added [Disinfect](https://github.com/genediazjr/disinfect) in PR #4 to deal with the fact we were susceptible to XSS attacks.
Disinfect not only deals with malicious content, it also escapes all content to make it safe for displaying in a browser. This means characters like `&`, `<` and `>` also get escaped. We're not worried about these in our data and feel it's for our clients to determine how to handle them in our responses.
So this change adds a new custom plugin that will unescape payloads after disinfect has escaped them.
> Add Unescape sanitized HTML characters plugin

- app/models/charge.model.js
I spoke to Sally and confirmed that `chargeValue` and `baselineCharge` in the Charge model should be integers. This change amends the Joi validation to enforce this.
> Amend chargeValue and baselineCharge to be integers

- app/services/calculate_charge.service.js
- test/services/rules.service.test.js
`CalculateChargeService` was one of the first bits of "calculate charge" work done. Subsequent discussion with @Cruikshanks has led to a re-evaluation of how we want it to work -- we now understand that we want to provide it with a presenter that it passes to the rules service and a translator to pass back to the caller. This change updates the terminology used in the service to reflect this, and adds some brief documentation to the service class.
> Update calculate charge service based on recent discussion

- app/plugins/index.js
- app/plugins/invalid_characters.plugin.js
- server.js
- test/features/invalid_characters.test.js
https://trello.com/c/xa2xIrRg
The existing [charging-module-api](https://github.com/defra/charging-module-api) checks for certain characters we've been told SOP considers invalid and can't handle.
However, it does this on an ad-hoc basis at the points we currently understand to be at risk. This has the effect of making some controllers more complex and adds duplication to the code.
On the basis our purpose is to collect and transform data before sending it onto SOP we think it's clearer to just reject any request that includes these invalid characters. There is less risk if we ensure none of our data contains them. It also simplifies the code and makes it easier to maintain.
So this change adds a custom plugin which checks for the invalid characters in any request. Unlike our previous …
> Add SOP data validation plugin

- .github/workflows/ci.yml
https://github.com/DEFRA/charging-module-api/pull/41
https://github.com/DEFRA/charging-module-api/pull/23
In PR #23 we added in a check to our CI for temporary tags. The original description was
---
The [Hapi Lab](https://github.com/hapijs/lab) test framework comes with the ability to run specific tests by adding `.only` to the describe block. For example
```javascript
describe.only('Sanitizing requests to the API', () => {
// ...
})
```
This is great! Just don't forget to leave them in when pushing your commits to GitHub. Having not learnt my lesson, this adds a check for use of this to the Travis build.
---
When we moved the CI to GitHub actions in PR #41 we lost the check. Having figured how to do it, this adds the check back in.
> Add back check for use of `only()` in tests to CI

- app/plugins/clean_payload.plugin.js
- test/features/clean_payloads.test.js
After merging we have spotted that the new custom `CleansePayload` plugin is filtering out properties which are boolean and set to `false`.
These are valid properties and should nto be filtered out. This change fixes the issue.
> Fix cleanse payload rejecting false booleans

- app/auth/jwt_strategy.auth.js
- db/migrations/20201012150934_create_authorised_systems.js
- db/seeds/02_authorised_systems.js
- test/support/helpers/authorised_system.helper.js
Prior to this change the ID of the authorised system record was actually the client ID generated by AWS Cognito.
We're trying to keep things as consistent as possible, so this change updates it to use a UUID as all our other tables do.
This means we need to add a new `client_id` field and use it to locate the authorised system record during the authorisation stage.
> Update authorised_systems to use conventional id

- app/models/authorised_system.model.js
- app/models/base.model.js
- app/models/index.js
- app/models/regime.model.js
> Most of the time you want the same configuration for all models and a good pattern is to create a `BaseModel` class and inherit all your models from that. You can then add all shared configuration to `BaseModel`.
[Objection documentation](https://vincit.github.io/objection.js/guide/models.html#models)
This work comes out of the spike we have been doing in [PR #48](https://github.com/DEFRA/sroc-charging-module-api/pull/48) adding authorisation systems and sorting out authorisation in the service.
We know we need to reference other models when creating the Objection relationships. But we also know there is the issue of [require loops](https://vincit.github.io/objection.js/guide/relations.html#require-loops). A base class helps resolve this because we can set the [modelPaths …
> Add new base model class

- app/models/authorised_system.model.js
- app/models/regime.model.js
- db/migrations/20201116103729_create_authorised_systems_regimes.js
An authorised system is a user in the context of our service. Any user that is not an admin requires specific authorisations to be granted for access to the different regimes. We hold a list of the available regimes. Each holds details such as their 'slug' (wrls, cfd, pas, and wml), name and Pre-SROC cutoff date.
So we need to create a many-to-many relationship between the two if we want to start properly authorising requests to none admin endpaths. We also need it to support adding new authorised systems (these changes will come in later PR's).
> Add many-to-many rel. for Auth. System and Regime

- app/auth/jwt_strategy.auth.js
- app/controllers/sroc/calculate_charge.controller.js
- app/plugins/payload_cleaner.plugin.js
- app/presenters/base.presenter.js
- app/services/calculate_charge.service.js
- app/services/cognito_jwt_to_pem.service.js
- app/services/object_cleaning.service.js
- app/services/rules.service.js
- test/presenters/base.presenter.test.js
- test/presenters/charge.presenter.test.js
- test/services/calculate_charge.service.test.js
- test/services/object_cleaning.service.test.js
- test/services/rules.service.test.js
We initially used `call()` as a convention for calling services and presenters. However this name clashes with JavaScript's predefined `call()` method. We are therefore changing the convention to `go()`, which this change implements across the existing services/presenters.
> Change .call() to .go()

- app/routes/calculate_charge.routes.js
- test/controllers/calculate_charge.controller.test.js
As we have started to migrate functionality from the [charging-module-api](https://github.com/defra/charging-module-api) we have also brought across the odd issue.
One of these is the charging-module's use of underscores in some of its endpoints. We are now [fixing the issue](https://github.com/DEFRA/charging-module-api/pull/164) there, so should it go live before this version we will not be lumbered with these 'unconventional' URL endpoints.
It's perfectly permissible to use underscores. However, it's definitely not the convention for URLs. To quote Google
> Consider using punctuation in your URLs. The URL **http://www.example.com/green-dress.html** is much more useful to us than **http://www.example.com/greendress.html**. We recommend that you use hyphens (-) instead of underscores (_) …
> Underscores in urls? Oh my!

- app/models/authorised_system.model.js
- app/models/base.model.js
- app/models/charge.model.js
- app/models/regime.model.js
- app/plugins/authorisation.plugin.js
- app/services/authorisation.service.js
- app/services/calculate_charge.service.js
- app/services/cognito_jwt_to_pem.service.js
- app/services/index.js
- app/services/object_cleaning.service.js
- app/services/rules.service.js
- test/features/authorisation.test.js
- test/services/authorisation.service.test.js
- test/support/helpers/authorised_system.helper.js
- test/support/helpers/index.js
- test/support/helpers/regime.helper.js
Currently, our authorisation mimics how authorisation should happen. It handles admin and public requests. But requests to 'regime' endpoints we mimic with a simple check that the username matches the requested regime.
What it should actually be doing is checking the requested regime against the regimes the system user is linked to.
Now we have the `RegimeModel` and `AuthorisedSystemModel` properly linked via [Objection](https://github.com/vincit/objection.js) we can do this.
This change adds a new service to handle the checking. We also needed to add a new regimes test helper to support this.
Another feature is we have to query the database for the regime as part of the checking. To avoid subsequent endpoints needing to do this we stash the `RegimeModel` instance in …
> Implement regime authorisation fully

- app/controllers/admin/regimes.controller.js
- app/presenters/index.js
- app/presenters/json.presenter.js
- app/services/index.js
- app/services/list_regimes.service.js
- test/controllers/admin/regimes.controller.test.js
- test/presenters/json.presenter.test.js
- test/services/list_regimes.service.test.js
We have currently settled on 2 key conventions
- our flow for all requests; `request -> translate -> model -> presenter -> response`
- all work the work of a controller endpoint will be done in a service
This change makes to additions to support this
- we add a `JsonPresenter` so even requests where we'll simply return the database result will flow through a 'presenter'
- we add a `ListRegimesService` to handle the work of querying for all regimes
> Start using service for regimes index endpoint

- app/controllers/admin/regimes.controller.js
- app/services/index.js
- app/services/show_regime.service.js
- test/controllers/admin/regimes.controller.test.js
- test/services/show_regime.service.test.js
Following on from [Start using service for regimes index endpoint](https://github.com/DEFRA/sroc-charging-module-api/pull/61) this creates a new service to handle querying the db for the requested regime.
Regimes are also linked to authorised systems. Unlike the list endpoint this will include the linked authorised systems in the response.
> Start using service for regimes show endpoint

- app/translators/bill_run.translator.js
- app/translators/index.js
- test/translators/bill_run.translator.test.js
This is the first step in being able to support a create bill run translator. When we have a request come in we'll need to be ale to validate it and map it to a model.
Adding a translator is the first step in being able to do this.
> Add pre-sroc bill run translator

- app/controllers/admin/authorised_systems.controller.js
- app/controllers/index.js
- app/plugins/router.plugin.js
- app/routes/authorised_system.routes.js
- app/routes/index.js
- app/services/index.js
- app/services/list_authorised_systems.service.js
- test/controllers/admin/authorised_systems.controller.test.js
- test/services/list_authorised_systems.service.test.js
We'll need an authorised systems controller to allow us to create new authorised systems records.
So as an initial step this change adds the initial controller along with an index endpoint which lists existing authorised systems.
> Add authorised systems index endpoint

- app/controllers/admin/authorised_systems.controller.js
- app/routes/authorised_system.routes.js
- app/services/index.js
- app/services/show_authorised_system.service.js
- test/controllers/admin/authorised_systems.controller.test.js
- test/services/show_authorised_system.service.test.js
Now we have an authorised systems controller with support for listing authorised system records we want the ability to view one in more detail. For example, include in the response the regimes the authorised system is authorised for.
This change adds the show endpoint to handle this.
> Add authorised systems show endpoint

- app/controllers/admin/authorised_systems.controller.js
- app/routes/authorised_system.routes.js
- app/services/create_authorised_system.service.js
- app/services/index.js
- app/translators/authorised_system.translator.js
- app/translators/index.js
- db/migrations/20201127100927_alter_authorised_systems.js
- test/controllers/admin/authorised_systems.controller.test.js
- test/services/create_authorised_system.service.test.js
- test/translators/authorised_system.translator.test.js
To support being able to add new users of the API we need an endpoint that allows us to create one.
This change adds a `POST` create authorised system endpoint to the controller.
> Add new create authorised system endpoint

- app/controllers/admin/health/database.controller.js
- app/controllers/index.js
- app/plugins/router.plugin.js
- app/routes/database.routes.js
- app/routes/index.js
- app/services/database_health_check.service.js
- app/services/index.js
- test/controllers/admin/health/database.controller.test.js
- test/services/database_health_check.service.test.js
This controller is more about confirming we can connect to a database in a given environment. But it will also allow us to access stats about each table, for example row counts and number of sequential scans. This information will be useful to monitor when the service goes live.
> Add database health check controller

- .env.example
- .github/workflows/ci.yml
- config/database.config.js
- db/create_database.js
- db/index.js
- knexfile.js
- package.json
When we created this project as a replacement for the [charging-module-api](https://github.com/defra/charging-module-api) we followed some of its existing practises as we were just getting started. One of them was to hardcode which database to use into the some of the npm scripts.
Knex and specifically its config file `knexfile.js` has the ability to maintain a number of different configurations. Which is used is determined by what `NODE_ENV` is set to.
By switching to use the `knexfile.js` properly we are not only being more consistent with our knex usage, we are also enabling more flexibility by not having to hardcode database names into the project.
> Use knex config to handle multiple environments

- app/controllers/index.js
- app/controllers/not_supported.controller.js
- app/routes/bill_run.routes.js
- test/controllers/not_supported.controller.test.js
- test/support/helpers/route.helper.js
This project is a replacement for the [charging-module-api](https://github.com/defra/chartging-module-api). It was originally intended as the means of implementing a new version of the charging rules and the requirements that go with it (SROC). But that has been postponed till 2022.
In the meantime, there are improvements to be made to the existing functionality, especially around the performance of generating the bill run. Plus we believe the design of this project is the only way we can support adding new regimes without duplicating all existing code. Duplication seems to be the only solution to adding regimes in the charging-module-api.
As these are large scale changes to the functionality we are doing them here so we at least have a 'working' version of the API for our first regime …
> Add not-supported controller to project

- docker-compose.yml
When working on the [charging-module-api Docker dev environment](https://github.com/DEFRA/charging-module-api/pull/175) we realised that the volume names used in the Docker compose were pretty generic. So resolved this in the charging-module by prefixing `cha_` to the names.
This change is just about solving the same issue in this project and ensuring we don't inadvertently overwrite or remove another service's volumes.
> Make docker dev environment more distinct

- db/index.js
https://trello.com/c/RIATlpAS
In the [charging-module-api](https://github.com/defra/charging-module-api) we hit an issue caused by integer overflow. We hold all our monetary values as pennies rather than pounds and pence. This is common practise in financial systems as it avoids some issues with rounding in equations.
The issue was all our monetary fields were set as `integer` but we found examples of bill runs with values larger than 2147483647 (the max an integer can hold). To solve the issue we needed to set the DB fields to `bigint`. [Bigint's](https://www.postgresql.org/docs/10/datatype-numeric.html#DATATYPE-INT) can hold values in the range of -9223372036854775808 to +9223372036854775807 in PostgreSQL.
JavaScript on the other hand uses …
> Automatically parse DB bigints as JavaScript Ints

- app/translators/index.js
- app/translators/transaction.translator.js
- test/translators/transaction.translator.test.js
As a first step to being able to add a Pre-SROC transaction to a bill run we need a translator. When we have a request come in we'll need to be able to validate it and map it to a model.
This change adds the translator.
> Add pre-sroc transaction translator

- app/services/create_authorised_system.service.js
> Immediately return this expression instead of assigning it to the temporary variable "regimes".
SonarCloud tagged some code as a code smell. Currently we assign a return value to a temporary variable then return it. We should be returning it directly.
This changes fixes the issue.
> Fix sonarcloud smell - return regimes directly

- app/auth/jwt_strategy.auth.js
- test/features/authentication.test.js
https://trello.com/c/DWZta7a6
In preparation for a thorough test of our authentication and authorisation functionality we did some exploratory testing ourselves. We found an issue where the service errors and returns a 500 when it should be returning a `401 - Unauthorized`.
If the token is valid (it is properly signed and not expired) but contains an unrecognised `client_id` we currently error.
This change fixes the issue. In this scenario we now will return a `401 - Unauthorized`.
> Fix not handling unknown client id

- app/auth/jwt_strategy.auth.js
- app/models/authorised_system.model.js
- test/features/authorisation.test.js
- test/models/authorised_system.model.test.js
- test/support/helpers/authorised_system.helper.js
https://trello.com/c/mjGotliI
When we migrated the authorised system functionality over we added a status column. The intent is we can use this to control an authorised systems access without having to remove the record.
As yet we don't know what the different statuses will be. What we do know is that only authorised systems with a status of 'active' should be able to access the service.
> Only allow 'active' authorised systems

- config/server.config.js
- server.js
Spotted when we built a Docker image for production and then tried to run it. We keep seeing this error
```
uncaught exception Error: Cannot find module 'hpal-debug'
Require stack:
- /home/node/app/app/plugins/hpal_debug.plugin.js
- /home/node/app/app/plugins/index.js
- /home/node/app/server.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
at Function.Module._load (internal/modules/cjs/loader.js:687:27)
at Module.require (internal/modules/cjs/loader.js:903:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/home/node/app/app/plugins/hpal_debug.plugin.js:23:19)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load …
```
> Fix reliance on dev-only dependencies in prod.

- app/plugins/index.js
In [Fix reliance on dev-only dependencies in prod.](https://github.com/DEFRA/sroc-charging-module-api/pull/95) we thought we had solved the problem of not calling out to dev-only dependencies by not registering dev-only plugins.
The problem is the index.js file in `app/plugins` is still requiring them, which means they, in turn, are trying to `require()` missing packages in the production Docker image!
So this change includes a fix to prevent this from happening.
> Fix dev dependencies in production - again!

- .github/workflows/ci.yml
- README.md
- docker-compose.yml
Currently the [charging-module-api](http://github.com/defra/charging-module-api) depends on version 10.6 of PostgreSQL. Our AWS environments are currently running that version and our original intent was to drop this version of the API in alongside until we are ready to switch.
Now we are working through so many changes as part of the performance rework with the intent of simply swapping out the old version we don't have that concern. So to take advantage of performance improvements in the latest version AWS RDS supports and to 'future-proof' the service for as long as possible we're going straight to PostgreSQL v12 when we deploy.
We won't have to change our Postgres related packages are they are on the latest already. But this change does update our development docker environment and CI …
> Update PostgreSQl dependence to v12

- app/presenters/create_bill_run.presenter.js
- app/presenters/index.js
- app/services/create_bill_run.service.js
- test/controllers/presroc/bill_runs.controller.test.js
- test/presenters/create_bill_run.presenter.test.js
- test/services/create_bill_run.service.test.js
The last part of adding bill run numbers to the create bill run endpoint is to define `create_bill_run.presenter` which we use to return to the end user the bill run id and number.
This change implements this and updates existing tests:
- `bill_runs.controller` now only tests for the info returned;
- `create_bill_run.service` now pulls the bill run from the database and tests its properties, rather than relying on all the properties being returned.
> Create Bill Run presenter

- config/server.config.js
- test/features/routing.test.js
This fixes an issue found after deploying the app to our AWS environments. Any requests to the service were returning a 404. When we checked the logs we found all the requests were being received with a trailing slash. For example, `GET https://myenv.cloud/status` was being recorded in the logs as `https://myenv.cloud/status/`.
This won't match to any of our routes hence the app returns a 404.
Some digging in the existing [charging-module-api](https://github.com/DEFRA/charging-module-api/blob/main/config/config.js#L27) confirmed it had made config changes to Hapi to deal with this situation. Our suspicion is that in the AWS API Gateway config for the environment something has inadvertently been set to add a trailing slash to the request before forwarding it to the app.
So the first change …
> Override default hapi router options

- package.json
It is best practice to randomise the order that tests are run in to help ensure that they're truly running in isolation and aren't just passing because of previous tests. This change adds the `--shuffle` parameter to `lab` to enable this.
> Add --shuffle parameter to lab

- db/migrations/20201127100927_alter_authorised_systems.js
- db/migrations/20201218153444_alter_authorised_systems.js
We have found an issue with `db/migrations/20201127100927_alter_authorised_systems.js`. In it's drop it's trying to add the column again, not drop it. This change fixes the issue.
We also have realised we are not marking a boolean field as `notNullable()`. Ideally, all boolean fields should be defaulted and never contain a null so we never have to worry about whether a value is `true, false, or null`. So this also adds an alter script for the `authorised_systems` 'admin' field.
> Fix issue with authorised system migration scripts

- app/translators/base.translator.js
- app/translators/transaction.translator.js
- test/translators/base.translator.test.js
- test/translators/transaction.translator.test.js
This change updates `transaction.translator` to remove validation duplicated in `create_charge.translator`. As part of this it amends `base.translator` to not error if data is passed in that isn't validated.
> Transaction translator

- db/migrations/20201217145238_alter_transactions.js
When we create a transaction proper there is a host more detail we are expected to retain about it, which comes from the original request and the result of the rules service. There also looks to be a host of duplication and redundant fields!
But for now, we need to replicate the existing charging module and get things working. So part of that is updating our `transactions` table to match the existing [charging-module-api](https://github.com/defra/charging-module-api) one.
This change covers an alter table migration to do that.
> Add alter transaction table migration

- app/plugins/index.js
- app/plugins/stop.plugin.js
- server.js
- test/features/graceful_shutdown.test.js
Our deployment is based on Docker and [AWS ECS](https://aws.amazon.com/ecs/). When ECS needs to stop a container it will send a [SIGTERM](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html) and allow it 30 seconds to stop.
> When UpdateService stops a task during a deployment, the equivalent of docker stop is issued to the containers running in the task. This results in a `SIGTERM` and a 30-second timeout, after which `SIGKILL` is sent and the containers are forcibly stopped. If the container handles the SIGTERM gracefully and exits within 30 seconds from receiving it, no `SIGKILL` is sent.
>
> https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/update-service.html
`SIGTERM` is a 'polite request' to stop. Typically it's caught by apps so they …
> Add stop (SIGTERM) plugin

- app/presenters/create_transaction.presenter.js
- app/presenters/index.js
- test/presenters/create_transaction.presenter.test.js
https://trello.com/c/gTcQmR8M
This change adds a create transaction presenter to the app. The presenter will specifically handle ensuring the result we return from a `POST - bill run transaction` matches what clients see when doing the same in the [charging-module-api](https://github.com/defra/charging-module-api).
> Add create transaction presenter

- app/translators/base.translator.js
- test/translators/base.translator.test.js
https://trello.com/c/gTcQmR8M
When a `POST Transaction` request comes in we first pass it to the transaction translator. It has 2 jobs to do
- validate the transaction properties
- translate the properties to those that match our db and model
Because of confusion on our part we thought we could pass the translator directly to the `CalculateCharge` service, which would then treat the object as if it was the payload to the calculate charge endpoint. Not only would this keep things simple it would also mean we would not need to duplicate the validation done for the charge properties.
We overlooked that the transaction translator is converting something like `waterUndertaker` to `regimeValue14`. The first thing the calculate charge service does is pass in the payload to …
> Allow access to validatedData in translators

- app/models/authorised_system.model.js
- app/models/index.js
- app/models/regime.model.js
- app/models/transaction.model.js
Spotted that the model for transactions was missing relationships we know it will now support. Plus its not listed by the `index.js` in the `app/models`. This change resolves those issues.
> Update transaction model relations

- app/presenters/calculate_charge.presenter.js
- app/translators/calculate_charge.translator.js
- app/translators/transaction.translator.js
- test/presenters/calculate_charge.presenter.test.js
When we were working on the spike in [PR #81](https://github.com/DEFRA/sroc-charging-module-api/pull/81) we had the intent of fixing some of the transaction field names to make them simpler and remove unnecessary prefixes.
We've decided to hold off on those changes and focus on ensuring we have things behaving as they currently do first. One of those changes that have managed to be implemented is referring to the `chargeCredit` field as `credit`.
To make things consistent with how the table has now been set up this small change rolls back the use of `credit` instead of `chargeCredit`.
> Fix charge credit vs credit in transaction

- app/presenters/rules_service.presenter.js
- app/translators/calculate_charge.translator.js
- app/translators/transaction.translator.js
- test/translators/calculate_charge.translator.test.js
When we were working on the spike in [PR #81](https://github.com/DEFRA/sroc-charging-module-api/pull/81) we had the intent of fixing some of the transaction field names to make them simpler and remove unnecessary prefixes.
We've decided to hold off on those changes and focus on ensuring we have things behaving as they currently do first. One of those changes that have managed to be implemented is referring to the `chargeFinancialYear` field as `financialYear`.
To make things consistent with how the table has now been set up this small change rolls back the use of `financialYear` instead of `chargeFinancialYear`.
> Fix chargeFinancialYear vs financialYear in trans.

- app/translators/calculate_charge.translator.js
- app/translators/transaction.translator.js
When we were working on the spike in [PR #81](https://github.com/DEFRA/sroc-charging-module-api/pull/81) we had the intent of fixing some of the transaction field names to make them simpler and remove unnecessary prefixes.
We've decided to hold off on those changes and focus on ensuring we have things behaving as they currently do first. One of those changes that have managed to be implemented is referring to the `chargePeriodStart` field as `periodStart`.
To make things consistent with how the table has now been set up this small change rolls back the use of `periodStart` instead of `chargePeriodStart`.
> Fix chargePeriodStart vs periodStart in trans.

- app/translators/calculate_charge.translator.js
- app/translators/transaction.translator.js
When we were working on the spike in [PR #81](https://github.com/DEFRA/sroc-charging-module-api/pull/81) we had the intent of fixing some of the transaction field names to make them simpler and remove unnecessary prefixes.
We've decided to hold off on those changes and focus on ensuring we have things behaving as they currently do first. One of those changes that have managed to be implemented is referring to the `chargePeriodEnd` field as `periodEnd`.
To make things consistent with how the table has now been set up this small change rolls back the use of `periodEnd` instead of `chargePeriodEnd`.
> Fix chargePeriodEnd vs periodEnd in trans.

- app/translators/rules_service.translator.js
- test/translators/rules_service.translator.test.js
Currently, the [charging-module-api](https://github.com/defra/charging-module-api) retains a formatted form of the response received from the charging module. This makes a lot of sense from an auditing context. Being able to show the calculation response if questioned about the charge value assigned is handy.
We want to do the same in this project so this change adds support for it. We do this by updating the `RulesServiceTranslator` to add it as a property. We know the properties of the translator will be assigned to a `TransactionTranslator` instance. That instance will then form the basis of what gets persisted to the db.
The one change we're making to the CHA is we are not doing any reformatting of the response. If the intent is to hold this for auditing purposes then we really should …
> Retain rules service response in translator

- app/translators/calculate_charge.translator.js
- app/translators/transaction.translator.js
- test/translators/calculate_charge.translator.test.js
- test/translators/transaction.translator.test.js
One of the changes we have made from the [charging-module-api](https://github.com/defra/charging-module-api) is that instead of using a boolean field to tell us whether something is related to `presroc` or not, we instead hold the ruleset name.
We believe this will give us much more flexibility going forward whilst still being able to tell us clearly which ruleset a transaction is related to. It also means we can use this value directly, for example, when trying to determine which rules service endpoints to hit.
As we only have `presroc` at the moment, this change adds it as a field to the `TransactionTranslator` and handles defaulting the value.
> Add default ruleset property to Trans. translator

- app/translators/transaction.translator.js
- test/translators/transaction.translator.test.js
We know we'll have a bill run ID because requests to create a transaction will come via `POST /v2/bill-runs/{id}/transactions`. We also will be persisting this to the `transactions` table when we create the transaction.
But the current design does not inject the bill run ID into the translator. Instead, it assumes this will be added separately when the transaction is persisted.
The issue is this forces us to generate an ad-hoc object to persist made up of the transaction translator, bill run ID, regime ID etc. It's not a significant problem but we believe a cleaner, clearer design is to think of a request not just as the body received. Instead, it should consider all information sent as being part of the request.
- the request body
- the regime it is for
- the authorised system making the …
> Update Trans. Translator to expect bill run id

- app/translators/transaction.translator.js
- test/translators/transaction.translator.test.js
This change updates the transaction translator to expect a regime Id as part of the data passed to it.
> Update Trans. Translator to expect Regime Id

- app/translators/transaction.translator.js
- test/translators/transaction.translator.test.js
This change updates the transaction translator to expect an authorised system Id as part of the data passed to it.
> Update Trans. Translator to expect Auth. System Id

- app/services/create_bill_run.service.js
- app/translators/bill_run.translator.js
- test/translators/bill_run.translator.test.js
This change updates the bill run translator to expect a regime Id as part of the data passed to it.
> Update Bill Run Translator to expect Regime Id

- app/services/create_bill_run.service.js
- app/translators/bill_run.translator.js
- test/translators/bill_run.translator.test.js
This change updates the bill run translator to expect an authorised system Id as part of the data passed to it.
> Update Bill Run Translator expect Auth. System Id

- app/translators/base.translator.js
We removed the logic which hid `_data` in the base translator in [PR #108](https://github.com/DEFRA/sroc-charging-module-api/pull/108). At the time we felt it was unnecessary as we had a convention of marking private members with an underscore.
However, in initial attempts to just pass the translator instances directly into [Objection insert queries](https://vincit.github.io/objection.js/guide/query-examples.html#insert-queries) we got errors. We are trying to avoid having to specify each field to insert or update and instead just rely on the translator instance and its properties. This failed though because `_data` was being seen and read by Objection. As our tables and models don't have a `_data` field the attempt failed. It works though if we hide `_data`.
So, this change reverts that …
> Revert making _data enumerable in base translator

- app/services/create_bill_run.service.js
- app/translators/bill_run.translator.js
- test/translators/bill_run.translator.test.js
We're trying to simplify and be consistent with the creation process for our records. In support of this, we're trying to have all values that are to be persisted determined in the translator. We then can pass the translator as is to the [Objection insert query](https://vincit.github.io/objection.js/guide/query-examples.html#insert-queries).
This change updates the BillRun translator and the create bill run service to follow this pattern.
> Manage values to persist in bill run translator

- app/services/create_authorised_system.service.js
- app/translators/authorised_system.translator.js
- test/translators/authorised_system.translator.test.js
Similar to the changes made in [Manage values to persist in bill run translator](https://github.com/DEFRA/sroc-charging-module-api/pull/119) we are trying to simplify and be consistent with the creation process of records. We want to be able to pass in translator instances to [Objection insert queries](https://vincit.github.io/objection.js/guide/query-examples.html#insert-queries) rather than spell out each field that needs updating.
We've made the change for when creating bill runs. At the moment the only other `create` is for authorised systems. This updates the `CreateAuthorisedSystemService` and associated `AuthorisedSystemTranslator` to support this new convention.
> Simplify auth. system creation in service

- app/services/calculate_charge.service.js
- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
This change updates the calculate charge translator to expect a regime 'slug' as part of the data passed to it.
> Update Calculate Charge Translator expect Regime slug

- app/services/calculate_charge.service.js
- test/services/calculate_charge.service.test.js
We're endeavouring to keep things simple, clean and avoid duplication. There are 2 places we need to acept a request, forward the details to the rules service, and return a response
- standalone calculate charge endpoint
- create a transaction endpoint
For both the flow is pretty similar right up to the point we get the result back from the rules service and translate it into something we understand.
- The standalone calculate charge then passes it to a presenter ready for returning to the client
- The create transaction needs the result in a format it understands for persisting to the database
We have experimented with changes to the presenters and translators, and even breaking up the charge service. However, we realised we were making the solution much more complicated simply to stick …
> Access rules service result from charge service

- app/presenters/calculate_charge.presenter.js
- app/translators/rules_service.translator.js
Spotted that when we get the result from the `RulesService` we are storing it in the `RulesServiceTranslator` as `sucFactor`. Our service understands this as `lineAttr4` on the transaction. We did have the translation listed. But we were also adding a `sucFactor` property. As can be seen in the subsequent line our convention in a translator _if_ we have to set a property is to use the translated name.
So this updates `RulesServiceTranslator` to fix this issue. The end result is when we use the translated fields in an [Objection insert query](https://vincit.github.io/objection.js/guide/query-examples.html#insert-queries) the fields will match what is in the table.
> Fix sucFactor from rules service not translated

- app/translators/rules_service.translator.js
- test/translators/rules_service.translator.test.js
Our test coverage has been showing a couple of lines always being missed in the `RulesServiceTranslator`. These were in the `_convertToPence()` method and were to handle if the param passed in was not a number.
In the context of the `RulesServiceTranslator` this would never happen. We use this method with `chargeValue` and `sucFactor` and the validation requires that they are numbers. We'd get a validation error before we ever attempted to pass in null to `_convertToPence()`.
So the first part of this fix is to remove the code that will never be used. Then whilst we were looking at `sucFactor` we spotted there was no specific test to confirm it gets converted to pence. So this change also adds a missing test for that.
> Add missing test coverage 4 RulesServiceTranslator

- app/controllers/index.js
- app/controllers/presroc/transactions.controller.js
- app/routes/transaction.routes.js
This was added at the start of the project as a demonstration of how we could structure our controllers across regimes. It doesn't have any functionality, and we are some way off actually implementing support for the transaction endpoints.
As we move towards this version 2 of the API being tested and put through its paces, we're taking this opportunity to remove something that is currently purely for demo purposes.
> Remove transactions controller

- db/migrations/20201224094044_alter_bill_runs.js
The staus for all bill runs when first created is set to 'initialised'. For other tables, we've set a default for the field so this change adds one for bill runs.
> Add default for status in bill run table

- db/migrations/20201203144442_create_transactions.js
- test/services/create_transaction.service.test.js
This adds a foreign key constraint on the `bill_run_id` field in the `transactions` table.
By adding the constraint in the table it means we don't have to query for a matching bill run every time a transaction is added. We can manage by exception those times when someone attempts to add a transaction for a bill run that does not exist. We do it this way for performance reasons.
> Add foreign key constraint to bill run id in trans

- db/migrations/20210108140838_alter_transactions.js
- test/features/bigint_handling.test.js
https://trello.com/c/HPENPD7d
We have previously faced an issue with the differences between what a PostgreSQL integer can hold and what a JavaScript one can. The issue was spotted when attempting to generate bill runs where the total value was more than 2147483647 pence.
We fixed it for bill runs. It was highlighted at the time that _if_ the calculated charge value for a single transaction was more than £21.4 million we'd face the same problem there. We put off updating the transaction because there are DB size and performance implications to using BigInts vs Integers. But latest intelligence shows though we've never had a single transaction for more than £21.4 million, proposed changes make it likely that we might.
So this change updates the relevant fields in the `transactions` table …
> Alter transactions to use BigInts

- app/translators/authorised_system.translator.js
- app/translators/bill_run.translator.js
- app/translators/transaction.translator.js
A rogue space had crept into some of the `'use strict'` declarations so they were `' use strict'` -- this change fixes that.
> Change some instances of ' use strict' to 'use strict'

- app/models/bill_run.model.js
- app/services/bill_run.service.js
- app/services/create_transaction.service.js
- app/services/index.js
- test/models/bill_run.model.test.js
- test/services/bill_run.service.test.js
- test/services/create_transaction.service.test.js
https://trello.com/c/gTcQmR8M
When adding a transaction to a bill run we should be checking the status of the bill run. If the bill run is `sent` or `billed` (admittedly statuses we're not using just yet) the request should be rejected. This is because the bill run is considered 'done'.
In coming changes we'll need to handle what we do with the bill run in other states. For example, when the summary has been generated we'll need to invalidate it and the relevant invoice and licence details when new transaction is added.
But for now this change is just focusing on ensuring you cannot add a transaction to a 'done' bill run.
> Add bill run status check to add transaction

- app/models/index.js
- app/models/invoice.model.js
- app/models/licence.model.js
- app/models/transaction.model.js
- app/services/create_transaction.service.js
- app/services/index.js
- app/services/licence.service.js
- db/migrations/20210111171826_create_licences.js
- db/migrations/20210112121936_alter_transactions.js
- test/features/bigint_handling.test.js
- test/services/licence.service.test.js
This implements `LicenceService` (along with a `Licence` model) and updates CreateTransactionService to use it. Creating a transaction now creates an licence if one doesn't already exist for the invvoice/customer/year and updates the licence stats (credit/debit count and value etc.)
> Add licence model and service

- app/services/bill_run.service.js
- app/services/create_transaction.service.js
- db/migrations/20210114152743_alter_bill_runs.js
- test/services/bill_run.service.test.js
This change implements bill run-level stats as follows:
- The `bill_runs` table now includes bill run stats columns (credit/debit count and value etc.)
- `BillRunService` accepts a transaction and returns updated stats
- `CreateTransactionService` saves these stats in the database
> Add summary to bill run service

- .dockerignore
We recently [made a change](https://github.com/DEFRA/sroc-charging-module-api/pull/150) to start using Knex's snake case mappers rather than Objection's.
To deal with migrations we needed to add a new `knexfile.application.js` file to the project. However, we neglected to update the Docker build, specifically the `.dockerignore` to ensure its included when the image is built.
This fix corrects the issue.
> Fix missing knexfile.application.js to docker

- .vscode/tasks.json
- Dockerfile
- docker-compose.yml
When we update the image in our AWS ECS environment, AWS starts a process of 'draining the swamp'. It stops sending requests to the old running containers and then asks them to stop. Meantime new containers are being started. The process seems to take a few minutes but it is a period of uncertainty. When I make a request, what version of the app and which Docker image is responding?
So this change is the first step in being able to get this information back. By adding the current git commit tag plus the Docker tag we generated into the image as we create it, we can include this information in the responses we send back. No more uncertainty!
> Add git and docker tags to Docker image

- app/services/bill_run.service.js
- test/services/bill_run.service.test.js
https://trello.com/c/YleRl9ts
In version 1 of the API, a check is made against the region of a transaction being added to ensure it matches the region of set against the bill run. We are not doing this check-in version 2. If a client did add a transaction with a different region to the bill run it would cause major problems upstream when the transaction file is generated and passed to SOP.
This change adds the check to the create transaction process.
> Add trans. region must match bill run check

- app/services/bill_run.service.js
- app/services/create_minimum_charge_adjustment.service.js
- app/services/invoice.service.js
- app/services/licence.service.js
- app/translators/transaction.translator.js
- db/migrations/20210126164808_alter_invoices.js
- db/migrations/20210126165247_alter_licences.js
- db/migrations/20210126165650_alter_transactions.js
- db/migrations/20210126170439_alter_bill_runs.js
- test/services/bill_run.service.test.js
- test/services/create_minimum_charge_adjustment.service.test.js
- test/services/invoice.service.test.js
- test/services/licence.service.test.js
- test/translators/transaction.translator.test.js
At present, we apply minimum charge to licences which are flagged as "new licences". However minimum charge may be more widely applied than this in future. We are therefore renaming `newLicence` wherever it occurs to `subjectToMinimumCharge`.
Future changes also mean that an invoice could potentially have a mix of transactions, some of which are subject to minimum charge and some of which aren't. Therefore we cannot guarantee that, for example, a licence with a credit value of `5000` is not subject to minimum charge; if `1000` of this is flagged as subject to minimum charge then a minimum charge adjustment would be needed to bring this portion up to `2500`. We are therefore also adding `subject_to_minimum_charge_credit_value` and `subject_to_minimum_charge_debit_value` fields at the bill …
> Minimum charge database changes

- app/translators/bill_run.translator.js
- test/services/create_bill_run.service.test.js
- test/translators/bill_run.translator.test.js
https://trello.com/c/MJ6w1HYe
When the region is missing from the create bill run payload we are returning a `500` when we should be returning a `422` with a nice error message.
This change fixes it.
<details>
<summary>Screenshot of fix result</summary>
</details>
> Fix create bill run returns 500 if region missing

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
https://trello.com/c/YleRl9ts
https://trello.com/c/xoHCMKqf
When adding a bill run transaction or calling the calculate charge endpoint if `compensationCharge` is true we are returning a `500` error.
This change fixes the issue.
> Fix 500 error when compensation charge set to true

- db/migrations/20210127145707_alter_transactions.js
- test/services/create_transaction.service.test.js
https://trello.com/c/FkpwxW8V
We allow client systems to provide a `clientID` in the create transaction request payload. In the [V1 charging-module-api](https://github.com/DEFRA/charging-module-api/pull/172) this is used to prevent a client system from accidentally adding a duplicate transaction.
The scenario is a client system attempts to add a transaction but it fails. They want confidence that if they try again, they won't mistakenly be adding a duplicate. The idea is we ensure this by blocking any attempt to add a transaction if its `regime_id` and `client_id` matches an existing transaction.
We have the field in the DB, and we accept and store the `client_id` in the current request. What we have not done is implement the blocking logic.
In V1 we added a service that queried the DB …
> Prevent duplicate transactions with clientID check

- app/translators/calculate_charge.translator.js
https://trello.com/c/YleRl9ts
https://trello.com/c/xoHCMKqf
If `volume` is not part of the create transaction request, or the request to calculate charge the rules service will still return a result. It is not a required field for it.
But we want to try and ensure that client systems are explicit in a request that will return a 0 charge. `volume` is the key factor in determining a WRLS charge result so we are happy to support `volume: 0`. But we want to avoid returning a £0 charge just because `volume` was inadvertently not part of the request.
This change updates the validation for `volume` to be `required()`.
> Raised as a fix because it should have been `required()` from the start.
<details>
<summary>Screenshot of response</summary>
</details>
> Fix ensure volume is required for charge and trans

- app/models/invoice.model.js
- app/services/calculate_minimum_charge.service.js
- app/services/create_minimum_charge_adjustment.service.js
- app/services/index.js
- test/services/calculate_minimum_charge.service.test.js
- test/services/create_minimum_charge_adjustment.service.test.js
The next stage of generating a bill run-level summary is to handle minimum charge. This branch introduces `calculateMinimumChargeService` which will handle checking whether minimum charge applies to the licences under a bill run, calculates the value of any adjustment transactions, and creates those transactions.
> Calculate Minimum Charge Transaction service

- app/translators/calculate_charge.translator.js
- package-lock.json
- package.json
- test/translators/calculate_charge.translator.test.js
For folks not aware, UK dates are written as either `YYYY-MM-DD` or `DD-MM-YYYY`. In the US month and day are reversed so they use `YYYY-DD-MM` or `MM-DD-YYYY`.
We use [Joi](https://github.com/sideway/joi) to validate our requests. What we have found is that when passed dates in certain formats it appears to use the US format rather than the UK. For example, it will see `01-04-2020` as 4 January 2020. `31-03-2020` will cause the API to return an invalid date error.
The convention with the API is that folks have been passing period end and start dates as `DD-MMM-YYYY`. But we don't want to force client systems to use only this format. We want to allow as many reasonable variations as possible.
We had hoped there would be a global 'catch-all' solution, either at the system or Joi level …
> Fix Joi validations using US date format

- test/controllers/presroc/bill_runs.controller.test.js
Spotted an opportunity to refactor how the request fixture is cloned in the `bill_runs.controller.test.js` test.
This reduces the duplication and makes it consistent with how we are doing things in newer tests.
> Refactor cloning in bill runs ctrlr test

- test/controllers/admin/authorised_systems.controller.test.js
- test/controllers/admin/regimes.controller.test.js
- test/presenters/create_bill_run.presenter.test.js
- test/presenters/create_transaction.presenter.test.js
- test/services/bill_run.service.test.js
- test/services/create_transaction.service.test.js
- test/services/generate_bill_run.service.test.js
- test/services/show_authorised_system.service.test.js
- test/services/show_regime.service.test.js
- test/support/helpers/general.helper.js
- test/translators/bill_run.translator.test.js
- test/translators/transaction.translator.test.js
We use UUID's as record ids in our database. PostgreSQL handles generating these for us when we insert a record. Some of our models have a requirement that linked item ID's are also populated. For example, a `transaction` expects its `invoice_id` and `licence_id` fields to be populated.
When testing though there are times we want to create a record without also having to create its dependents. So far we have been using hardcoded UUID's specified within the tests. But we foresee tests where we may need to create a number of items so managing lists of UUID's will become unmaintainable.
This change adds a UUID4 generator to our current `GeneralHelper` and updates the existing tests to use it where applicable. We will then have this available for those tests that need valid but meaningless …
> Add uuid4 generator to test GeneralHelper

- app/plugins/db_errors.plugin.js
- app/plugins/index.js
- app/services/db_errors.service.js
- app/services/index.js
- server.js
- test/controllers/presroc/bill_runs.controller.test.js
- test/services/db_errors.service.test.js
Currently, any database errors result in a generic `500` response from the API. We see the actual error in the logs and in Errbit. But it's a poor experience for the client system. There are also scenarios where a DB error is expected, for example, if you try and add 2 transactions with the same regime and client ID.
When these occur we want our responses to be more meaningful but we also don't want to pollute the code with duplicate `try/catch` blocks all over the place. So, instead this change will add a new plugin that will add an `onPreResponse` hook. It will check for database errors and generate meaningful Boom errors for the scenarios it expects. For those it doesn't it will attempt to return something moe meaningful than a generic `500`.
> Add Database error plugin

- app/services/authorisation.service.js
- db/seeds/02_authorised_systems.js
- test/controllers/admin/regimes.controller.test.js
- test/services/authorisation.service.test.js
- test/services/show_authorised_system.service.test.js
- test/support/helpers/authorised_system.helper.js
- test/support/helpers/route.helper.js
> The short version! If you are an admin user, the regime doesn't get populated so lots of functionality goes 'pop'!
It was spotted during testing that if an attempt is made, for example, to create a bill run for a regime but the client ID used is an `admin` then a `500` response is returned and the request fails.
We've quickly spotted the issue. All `admin` authorised systems are automatically granted access to all regimes. So, when we first implemented authorisations we didn't see the need to link `admin` users to regimes within the database. Our `AuthorisationService` would see an `admin` and respond with ***go!***.
As we have iterated, we've added functionality that determines the regime for paths where its required and adds it to `request.app`, the place recommended by Hapi to store …
> Fix admin requests to regime paths return 500

- app/plugins/index.js
- app/plugins/version_info.plugin.js
- server.js
- test/features/version_info.test.js
This is the second part of providing version information about the app and the docker image being used to a response. The first covered [adding git and docker tags to the image](https://github.com/DEFRA/sroc-charging-module-api/pull/155).
With the access we have, we can't confirm for certain which of our docker images provided a response. We can make assumptions based on when the AWS ECS task definition was last updated. But for a period after the update, there is always some uncertainty.
By building the information into the docker image and providing it in every response we can be certain whatever the circumstances. So, this change adds a new plugin that will handle this new feature.
<details>
<summary>Example of headers</summary>
</details>
> Add version info to responses plugin

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
https://trello.com/c/xoHCMKqf
When we first implemented the validation for a charge (the data we send to the rules service to calculate a charge) we simply copied what [version 1](https://github.com/defra/charging-module-api) does.
It has a validation rule which requires `eiucSource` be populated if `compensationCharge` is `true`. For `waterUndertaker`, the rule is simply that it is mandatory.
In fact, the business rule is
> `EIUC Source` and `Water Undertaker` are mandatory for a compensation charge only (i.e. only where `Compensation Charge` is set to TRUE)
Our QA @anwarisse1 spotted during the testing of both version 1 and version 2 this oversight in the validation rules.
This change fixes the issue in this version.
> Fix waterundertaker validation on charge

- db/migrations/20210131154912_alter_bill_runs.js
https://trello.com/c/Z6bexoqw
As part of the **Generate bill summary** work we need to calculate the total number of credit notes and invoices for a particular bill run.
We know that the invoice and credit values need to be `bigint` thanks to userability tests on [version 1](https://github.com/defra/charging-module-api). But we didn't spot when we wrote the migrations that the count columns are also set to `bigint`.
Put simply, we've not really designed and architected this project for handling more than 2147483647 invoices in a single bill run!
So, to make the count columns consistent with what we have done on the `invoice` and `licence` tables this change fixes the migration that added them to the bill runs table.
> Fix bill runs credit and invoice count column type

- app/controllers/presroc/bill_runs.controller.js
- app/routes/bill_run.routes.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/XNqxpZto
This is the first step in adding a `GET /v2/{regime}/bill-run/{id}/status` endpoint to the API.
Before a client system can perform certain actions, the bill run needs to be in the correct state. This endpoint will allow a client system to quickly check just the status of the endpoint, rather than use an endpoint like `GET /v2/{regime}/bill-run/{id}` and all the extra data it pulls through.
There are also actions which are not instantaneous like `/generate`. This endpoint will be more suitable for client systems to 'poll' in order to confirm if the action has completed.
This change does not include logic. It simply adds the controller, route and a basic test. We can then use this as a base to build on.
> Add stand-in bill run /status endpoint

- app/services/bill_run_status.service.js
- app/services/index.js
- test/services/bill_run_status.service.test.js
https://trello.com/c/XNqxpZto
This is the second step in adding a `GET /v2/{regime}/bill-run/{id}/status` endpoint to the API.
Our convention is to do all work in a service rather than directly in the controller. So, even though it's not the largest of tasks, this change adds a `BillRunStatusService` to the project.
> Add bill run status service

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
Our business rules state that some values should only have a maximum of 3 decimal places. When we re-tested [Version 1](https://github.com/defra/charging-module-api) we found it wasn't doing this validation so we double-checked if it is necessary.
In the case of `section126Factor` it does need to be validated to 3 decimal places. The rules service can handle up to 15. But the transaction file we generate and export has a hard limit of 3 decimal places for this field. So, that is why we are forced to limit the level of precision.
`volume` was the other case. It has a limit of 150 characters in the file and no fixed format!. The rules service's 15 decimal limit still applies but we are happy to let it do the validation.
So, this change fixes the validation for `section126Factor`.
> Fix section126Factor in CalculateChargeTranslator

- app/presenters/bill_run_status.presenter.js
- app/presenters/index.js
- app/services/bill_run_status.service.js
- test/presenters/bill_run_status.presenter.test.js
https://trello.com/c/XNqxpZto
This is the third step in adding a `GET /v2/{regime}/bill-run/{id}/status` endpoint to the API.
Our convention is to use a **presenter** to convert data from the service into a response client systems expect. So, even though it's the simplest of conversions, this change adds a `BillRunStatusPresenter` to the project.
> Add bill run status presenter

- app/routes/bill_run.routes.js
- test/controllers/presroc/bill_runs.controller.test.js
Clearly, @cruikshanks was not paying attention when he reviewed and approved [Create Generate Bill Run Summary endpoint](https://github.com/DEFRA/sroc-charging-module-api/pull/151). The endpoint has been added as a `POST` request when it should have been a `PATCH`.
We are trying to stick to a convention of
- `GET` for any request to view data. The request should also result in no action or changes to the data
- `POST` for any request to create a new record
- `PATCH` for any request which requires no payload, and initiates an action in the service
The `../bill-runs/{id}/generate` meets the criteria for a `PATCH` and we should have added it as such. This change fixes the mistake @cruikshanks let through 😱🤦
> Fix bill run generate request type (PATCH vs POST)

- app/controllers/presroc/bill_runs.controller.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/XNqxpZto
This is the final step in adding a `GET /v2/{regime}/bill-run/{id}/status` endpoint to the API.
In this change we hook the `BillRunStatusService` we created to the new `/status` controller we added in the first step.
> Hook bill run status service to controller

- app/models/invoice.model.js
- app/services/calculate_minimum_charge.service.js
- app/services/generate_bill_run.service.js
- test/services/calculate_minimum_charge.service.test.js
- test/services/generate_bill_run.service.test.js
- test/support/helpers/rules_service.helper.js
It was found during testing that invoices were being flagged up as minimum charge when they shouldn't have been. This change aims to resolve this:
- We add additional checks to the `InvoiceModel.minimumCharge` modifier to ensure that a minimum credit or debit value does exist;
- We test that a minimum charge value is required before attempting to create a minimum charge transaction.
Note that `rulesServiceHelper.mockValue` has been amended as part of this to help with test -- it now accepts values in pence for consistency (with affected tests changed to reflect this), and it returns a Sinon stub that we can use to `.restore()` the original behaviour before we stub it again (otherwise, we'd need to `Sinon.restore()` which would revert _all_ stub behaviour -- not an issue at present but it …
> Fix minimum charge issues in generate bill run

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
The rules around `waterUndertaker` in the create transaction and calculate charge requests are a bit complex. If `compensationCharge` is `true` then `waterUndertaker` must be present and a boolean.
If `compensationCharge` is false, we don't really care. However, it seems the rules service does. Even though it's not needed for the calculation if we send anything other than a boolean value the rules service throws a 500.
That wouldn't be too bad if it also had a useful error message that highlighted `waterUndertaker` as the problem. But it doesn't. 😩
So, we want to avoid our client systems getting any error where the cause is unclear. This change adds validation for `waterUndertaker` so that if present it at least ensures its a boolean.
> Validate water undertaker is boolean in charge

- app/controllers/presroc/bill_runs.controller.js
- app/services/generate_bill_run.service.js
- test/services/generate_bill_run.service.test.js
To help monitor the time taken to generate a bill run, we're adding a feature to log the time it takes.
`GenerateBillRunService` now takes an optional `logger`, intended to be the server `logger` object. If it's present, the service will use the logger's `info` method to log the time taken to generate the bill run.
> Output generate bill run timing

- app/models/invoice.model.js
- test/models/invoice.model.test.js
- test/services/generate_bill_run.service.test.js
- test/support/helpers/invoice.helper.js
We spotted during testing that the deminimis Objection query modifier in the `InvoiceModel` was not behaving as expected.
The scenario was we had added 3 transactions for the same invoice, all with a value of £1.26. The net value is £3.78 so it should be subject to deminimis. However, the `GenerateBillRunService` didn't pick it up because the modifier included the clause `credit_value - debit_value > 0`. In this scenario that would be
```
((0 - 378) = -378) > 0
```
By reversing the calculation, the modifier should behave as expected
```
((378 - 0) = 378) > 0
```
This change applies the update and looks at some tests to cover this in future.
> Fix Invoice deminimis query modifier

- app/models/bill_run.model.js
- app/presenters/index.js
- app/presenters/view_bill_run.presenter.js
- app/services/index.js
- app/services/view_bill_run.service.js
- test/services/view_bill_run.service.test.js
We want to set up a 'View Bill Run' endpoint, and the first stage of this is setting up `ViewBillRunService`. This accepts a bill run id and returns the data ready to be returned to the requesting user.
> Create View Bill Run Service

- app/controllers/admin/test/test_bill_run.controller.js
- app/controllers/index.js
- app/plugins/router.plugin.js
- app/routes/index.js
- app/routes/test.routes.js
- test/controllers/admin/test/test_bill_run.controller.test.js
- test/support/generators/README.md
- test/support/generators/bill_run.generator.js
- test/support/generators/index.js
- test/support/helpers/route.helper.js
There are times we need to check the performance of certain actions on large data sets, for example, how long the generate process takes.
We have external tests that can create bill runs and the associated transactions but they are either limited in how many they can add, or where they can be used. They also come with the overhead of waiting for each transaction request to be sent and completed.
Ideally, we could do with a way of creating a bill run without the overhead of sending requests across the network. This new endpoint does exactly that. When called, it will generate bill runs that feature a mix of invoices and licences, plus ones that will be identified as zero value, deminimis, and minimum charge. We can then test and assess viewing, generating, approving, and sending bill runs …
> Add test only bill run generator

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
Whilst testing the `/generate` bill run endpoint we came across a situation where the `source`, `season`, and `loss` values were found to be invalid. Yet the rules service still returned a 'valid' result. Hidden away in the response was a message telling us that the values we had sent through did not match those in the rules service.
After some investigation, we found it was purely the 'case' of the strings that were used causing the problem. The values were fine.
So, we are doing 2 things
- we are updating the [SROC Charging Module API](https://github.com/defra/sroc-charging-module-api) to automatically 'title case' any values sent through
- we are also updating it to check for messages from the rules service and respond appropriately
This change covers the first point; converting the …
> Title case loss, season & source values in charge

- app/models/bill_run.model.js
Whilst working on [Fix update of invoice for minimum charge](https://github.com/DEFRA/sroc-charging-module-api/pull/200) we spotted that the bill run and licence are not being properly updated either.
Having created and generated a bill run in our tests, we need to grab the related invoices, licences and transactions so we can test our assertions. But we currently cannot do this for licences because there does not appear to be an Objection relationship setup between the 2.
This change fixes the issue.
> Fix missing bill run to licence relationship

- app/services/bill_run.service.js
- app/services/create_minimum_charge_adjustment.service.js
- app/services/generate_bill_run.service.js
- test/services/bill_run.service.test.js
- test/services/generate_bill_run.service.test.js
During the bill run generate process if an invoice is subject to minimum charge and either its debit or credit value is below £25 we add an additional transaction to make the value up to £25.
The thing to note is we do this for _both sides_ if there is a credit and a debit value. This means we also need to update the debit and credit counts and values in the invoice and bill run record to reflect the new transactions we created.
In testing, though we have found only one side will be updated, dependent on whichever minimum charge transaction is created last.
The cause is a mix of needing to do things within a transaction and attempting to patch an instance of each record type (bill run, invoice, licence).
Currently, the order of events is
- create the minimum charge transactions
- iterate …
> Fix update of invoice for minimum charge

- app/services/generate_bill_run.service.js
[Output generate bill run timing](https://github.com/DEFRA/sroc-charging-module-api/pull/196) has already proved to be a massive help in understanding how long the generate bill run process takes. But we did spot one more tweak that would make it perfect; including the bill run ID in the log output.
> Add bill run ID to generate bill run time logging

- app/services/generate_bill_run.service.js
- test/services/generate_bill_run.service.test.js
- test/support/generators/bill_run.generator.js
If an error occurs during the 'generate bill run' process it will cause the app to crash.
We first noticed this kind of behaviour when working on [Add test only bill run generator](https://github.com/DEFRA/sroc-charging-module-api/pull/199)
> At first [the error] was confusing (we're using Boom!) but then we understood. Whilst we are within the lifecycle of the Hapi request and doing things synchronously any errors we throw or that are thrown are captured by Hapi which then wraps them as Boom `500` errors (if they are not already boom errors).
>
> However, because we have set up the generator to 'kick-off' the generate process asynchronously and then immediately respond all bets are off. Now any errors that are thrown are outside of the lifecycle have nowhere to go. Hence, when they …
> Add error handling to GenerateBillRunService

- app/models/invoice.model.js
- db/migrations/20210215154015_alter_transactions_and_invoices.js
- test/models/invoice.model.test.js
As part of the work of getting view bill run in line with the [draft spec](https://app.swaggerhub.com/apis-docs/sro/sroc-charging-module-api/draft#/billrun/ViewBillRun), we need to make a few changes to the `transactions` and `invoices` tables:
- `transaction_reference` is actually an invoice-level reference so we drop the column from the `transactions` table and add it to the `invoices_table`.
- `transaction_type` is also invoice-level so we drop the column from the `transactions` table. It contains `C` if the invoice is a net credit or `I` if it is a net debit, so instead of creating a column to the `invoices` table we instead add a `$transactionType` method to the `Invoices` model to generate it dynamically.
- While we're making amendments to the `transactions` table, we note that the …
> Amend transactions and invoices tables

- app/services/generate_bill_run.service.js
- app/services/view_bill_run.service.js
- db/migrations/20210212160135_alter_invoices.js
- test/services/generate_bill_run.service.test.js
According to the [draft API docs](https://app.swaggerhub.com/apis-docs/sro/charging-module_api/draft), viewing the bill run should return a `minimumChargeInvoice` flag at the invoice level, which isn't currently included in `ViewBillRunService`. This change amends `GenerateBillRunService` to implement it.
Note that it does this a little differently to the other invoice-level flags, `zeroValueInvoice` and `deminimisInvoice`, which are set by querying the db to return the relevant invoices and `patch`ing them to set the flag. For `minimumChargeInvoice`, we set this invoice-level flag when we update the invoice figures as part of the process of saving minimum charge adjustment transactions to the db.
> Minimum charge invoice flag

- app/controllers/presroc/bill_runs.controller.js
- app/routes/bill_run.routes.js
- test/controllers/presroc/bill_runs.controller.test.js
The last step of implementing the View Bill Run functionality is to create an endpoint and hook its controller up to the `ViewBillRunService`, which is what we do in this change.
> Add view bill run endpoint using ViewBillRunService

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
https://trello.com/c/Xz1R1zEf
It was noted when reviewing some data from WRLS recently that some charges have the same start and end period dates. Discussions with the WRLS team and the business confirmed this does happen and is acceptable.
So, this change alters the validation so that the `periodStartDate` when creating a transaction or calculating a charge can be the same (not just less than) the `periodEndDate`.
> Allow period start to be same as period end date

- app/controllers/presroc/bill_runs.controller.js
- app/routes/bill_run.routes.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/0m5idNGk
This is the first step in adding a `GET /v2/{regime}/bill-run/{id}/transactions/{id}` endpoint to the API.
Client systems need to see all the details we hold for a transaction. This change adds the endpoint that will be used, plus a basic test. But none of the logic to actually find and present the transaction is yet included.
> Add stand-in view bill run transaction endpoint

- Dockerfile
- hooks/README.md
- hooks/build
https://trello.com/c/jHORNdnQ
We have been asked to start making available this project's Docker images so the WRLS team have the means to start working with the new version and migrating their code to use it.
We have done this before with [version 1 of the API](https://github.com/defra/charging-module-api) by creating a [repository on Docker Hub](https://hub.docker.com/r/environmentagency/charging-module-api) and pushing each release image to it.
This was fine for v1 where there were months between releases. But both teams are actively working on switching away from V1, so releases should now come thick and fast as new endpoints are added and fixes and improvements are made.
Docker Hub can be linked to your repo which then allows [Automated …
> Add support for automated builds in Docker Hub

- .env.example
- config/authentication.config.js
- db/seeds/02_authorised_systems.js
https://trello.com/c/jHORNdnQ
When creating an environment from scratch, which we'll often do locally, without fail we'll spend 5 minutes wondering why nothing is working!
It's because we always forget to seed what we refer to as the 'system user'. Basically, a non-admin user that has the same client ID as the AWS Cognito user created for WRLS in that matching environment.
This change hopes to do away with that by adding a seed file that will populate the system user if the env var `SYSTEM_CLIENT_ID` is present.
> Add system user seed

- app/presenters/view_bill_run.presenter.js
https://trello.com/c/XgM2gCbm
This came up when building the view bill run endpoint. The `ruleset: 'presroc'` property is V2's version of the `presroc: true/false` property in V1.
Our issue is what ruleset to use is determined at the transaction, not bill run level. So, we checked in with the team's BA and confirmed that a bill run can include transactions calculated using different rulesets (when we finally have them). It is never going to be set at bill run level.
This change removes it from the view bill run response as it makes no sense at that level.
> Remove pre-sroc (ruleset) from view bill run

- .vscode/tasks.json
- package.json
We currently have run scripts for creating the database and running migrations in a new environment. But we don't have one for seeding the database. It is on new users to the project to work out what the relevant knex command should be.
We have also spotted some unexpected behaviour when you seed a standalone docker-compose based environment. In this situation we would run `docker-compose exec app npx knex seed:run` from a [makefile](https://en.wikipedia.org/wiki/Makefile). When we do though we see
```
$ make seed
docker-compose exec app npx knex seed:run
Need to install the following packages:
knex
Ok to proceed? (y) y
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: …
```
> Add seed run script to package.json

- app/controllers/admin/test/test_transactions.controller.js
- app/controllers/index.js
- app/routes/test.routes.js
- app/services/index.js
- app/services/show_transaction.service.js
- test/controllers/admin/test/test_transactions_controller.test.js
- test/services/show_transaction.service.test.js
https://trello.com/c/0m5idNGk
This is actually a re-think of the [Add stand-in view bill run transaction endpoint](https://github.com/DEFRA/sroc-charging-module-api/pull/211). [Version 1](https://github.com/defra/charging-module.api) of the API has view bill run transaction endpoint through discussions with the WRLS team have confirmed it's not used by them.
The main driver for replicating it in Version 2 of the API has actually been to support testing; our lead QA @anwarisse1 needs a view of the transaction to confirm everything is populated as expected in a range of scenarios.
So, we started PR #211 with the intent of providing a client-focused endpoint, even though WRLS re-confirmed they wouldn't use it and knowing it was just a priority for testing. They also confirmed they only want …
> Add admin test view transaction endpoint

- app/controllers/presroc/bill_runs.controller.js
- app/routes/bill_run.routes.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/SmiI8YaG
This is the first step in adding a `PATCH /v2/{regime}/bill-run/{id}/approve` endpoint to the API.
The roots of this project are based on the work done on the [sroc-tcm-admin](https://github.com/DEFRA/sroc-tcm-admin) service. In that service, individual transactions would need to be approved first at which point they would be included in the next 'bill run' (though it doesn't use that term).
As this API has been developed to serve the WRLS service first, 'bill runs' and creating them first before adding transactions to them came to the fore. But the idea of needing to 'approve' transactions has remained.
The overall need is to add an endpoint that allows the transactions linked to a bill run to be mass approved. This change gets things started with a stand-in …
> Add stand-in approve bill run endpoint

- app/models/bill_run.model.js
- app/services/approve_bill_run.service.js
- app/services/index.js
- test/services/approve_bill_run.service.test.js
https://trello.com/c/SmiI8YaG
As part of adding an endpoint to 'approve' bill runs, we need a service that actually does the work of checking if a bill run is in the right status to be approved, and then marks it as so.
This change adds that service!
> Add approve bill run service

- app/controllers/presroc/bill_runs.controller.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/SmiI8YaG
This finishes off the work on a new `/v2/{regimeId}/bill-runs/{billRunId}/approve` endpoint.
We hook up the new `ApproveBillRunService` to the endpoint and check our tests.
> Hook up approve bill run endpoint to service

- app/presenters/view_bill_run.presenter.js
- test/services/view_bill_run.service.test.js
Spotted in recent testing that in the view bill run presenter we return `zeroValueLineCount` but at the invoice and licence level, we just do `zeroLineCount` i.e. the actual name of the field.
This small change just corrects the inconsistency.
> Correct view bill run zero line count property

- app/services/generate_bill_run.service.js
- test/services/generate_bill_run.service.test.js
While developing [`DeleteInvoiceService`](https://github.com/DEFRA/sroc-charging-module-api/pull/221) we realised that `invoiceValue` was being calculated incorrectly in cases where minimum charge applies. This change aims to resolve this.
> Fix invoiceValue for minimum charge

- app/controllers/presroc/bill_runs_invoices.controller.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
https://trello.com/c/r9UClZob
This finishes off the work on a new `GET /v2/{regimeId}/bill-runs/{billRunId}/invoices/{invoiceId}` endpoint.
We hook up the new `ViewBillRunInvoiceService` to the endpoint and check our tests.
> Hook up view bill run invoice endpoint to service

- app/presenters/view_bill_run.presenter.js
An artefact of [version 1](https://github.com/defra/charging-module-api) was that the bill run record had an `approved_for_billing` flag separate from the bill run status.
As part of the improvements we have been doing to Version 2 we have managed to drop the need for this, specifically with the work we have done in [Add approve bill run service](https://github.com/DEFRA/sroc-charging-module-api/pull/237).
But as we were not sure what we'd be doing when we developed the view bill run endpoint, we still have this as a property in the `ViewBillRunPresenter`.
This change drops it from the presenter.
> Remove approvedForBilling from view bill run

- app/models/bill_run.model.js
- app/services/delete_invoice.service.js
- test/services/delete_invoice.service.test.js
An additional consideration when deleting an invoice from a bill run is that we want to ensure the bill run status reverts to its `initialised` state if there are no invoices left. This change implements this.
> Update bill run status when last invoice is deleted

- app/controllers/admin/test/test_bill_runs.controller.js
- app/controllers/presroc/bill_runs_transactions.controller.js
- app/services/bill_run.service.js
- app/services/create_transaction.service.js
- test/controllers/presroc/bill_runs.controller.test.js
- test/services/bill_run.service.test.js
- test/services/calculate_minimum_charge.service.test.js
- test/services/create_minimum_charge_adjustment.service.test.js
- test/services/create_transaction.service.test.js
- test/services/delete_invoice.service.test.js
- test/services/generate_bill_run.service.test.js
- test/services/show_transaction.service.test.js
- test/services/view_bill_run.service.test.js
- test/support/generators/bill_run.generator.js
A follow up to [Remove redundant bill run 'gets' and 'checks'](https://github.com/DEFRA/sroc-charging-module-api/pull/233) we've spotted that the `BillRunService` both fetches the bill run and then performs the same checks that the bill run plugin is doing via `RequestBillRunService`.
This change removes these redundant calls.
> Found as part of [Spike - Investigate deadlock issues with bill runs](https://github.com/DEFRA/sroc-charging-module-api/pull/247)
> Remove bill run fetch and checks in BillRunService

- app/services/show_transaction.service.js
- test/services/show_transaction.service.test.js
To help with testing it's been requested that we add the signed value of `chargeValue` to the test `ShowTransactionService`. This change implements this by adding `signedChargeValue`.
> Add signedChargeValue to ShowTransactionService

- app/services/create_transaction_tally.service.js
- app/services/index.js
- test/services/create_transaction_tally.service.test.js
When we add a transaction to a bill run we also update 'tally' values in the related bill run, invoice and licence records.
We were already aware of duplication across the `BillRunService`, `InvoiceService` and `LicenceService` for handling this. Now, as part of performance improvements identified in [Spike - Investigate deadlock issues with bill runs](https://github.com/DEFRA/sroc-charging-module-api/pull/247) we need to change the way it's done.
So, we're taking the opportunity to put the functionality into a new service that can then be reused. The new service needs to generate a 'patch' object that can be used with an Objection model's static `query().patch()` method. We have found updating a model in this way, versus using the instance `$patch()` method, gives a slight performance …
> Add CreateTransactionTallyPatchService

- app/services/generate_bill_run_validation.service.js
- test/services/generate_bill_run_validation.service.test.js
https://trello.com/c/TNehNlxK
This came up as an edge case we had not considered when generating bill runs. What should we do if a request to `/generate` is received for a bill run that has a status of 'generated'?
Whilst we believe running the process for a second time would not change the generated bill run values, we've decided it would be more prudent to just not allow this. We certainly cannot think of a scenario where this would be needed so there is no question regards needing to support it.
So, this change adds a new check to `GenerateBillRunValidationService`. If the `status` is generated we will return a `409` in the same way we do if the status is `generating`.
> Handle call to /generate for generated bill run

- app/models/bill_run.model.js
- app/models/invoice.model.js
- app/services/index.js
- app/services/next_file_reference.service.js
- app/services/next_transaction_reference.service.js
- app/services/send_bill_run_reference.service.js
- db/migrations/20210305132500_alter_bill_runs.js
- test/models/bill_run.model.test.js
- test/models/invoice.model.test.js
- test/services/send_bill_run_reference.service.test.js
- test/support/helpers/invoice.helper.js
https://trello.com/c/kU8RWnKq
As part of implementing the PATCH /v2/{regimeId}/bill-runs/{billRunId}/send endpoint we need a service that manages generating transaction and file references and applying them to the invoices and bill run.
This change adds the service.
> Add SendBillRunReferenceService

- app/controllers/presroc/bill_runs.controller.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/kU8RWnKq
This is the final step in implementing the `PATCH /v2/{regimeId}/bill-runs/{billRunId}/send` endpoint.
We just need to hook up our standin endpoint to the new `SendBillRunReferenceService`.
Note - In a future iteration we will also trigger creating of the export file as a background task. However, there is additional work that needs to be done first before this can happen. The scope of the endpoint right now is to get the bill run ready for being exported.
> Hook up /send bill run endpoint to new service

- app/services/generate_bill_run.service.js
- test/services/generate_bill_run.service.test.js
https://trello.com/c/pswT0yjy/1905-identify-de-minimis-invoices-v2
The defect was raised as deminimis invoices were being included in the counts and values returned at the bill run level for the invoices belonging to it.
We resolve this by:
- Changing the order of bill run generation so that deminimis flags are set before summarising invoices;
- Adding a condition to the query that retrieves debit invoices so that it doesn't include invoices flagged as deminimis.
> Fix deminimis invoices being included in bill run figures

- app/models/invoice.model.js
- test/services/generate_bill_run.service.test.js
https://trello.com/c/GraJh0f7/1904-identify-zero-value-invoices-v2
The acceptance criteria specifically refer to _net_ zero value invoices (ie. where the invoice debit value minus the invoice credit value is 0), whereas the existing behaviour is to only mark invoices as a zero value if they contain solely zero value transactions. This change therefore updates the `zeroValue` modifier of `InvoiceModel` to `debit_line_value - credit_line_value = 0` so that net zero value invoices are correctly identified and `zeroValueInvoice` therefore set to `true`.
Note that a [previous discussion regarding v1](https://trello.com/c/9DvL0KtU/378-exclude-invoices-with-net-zero-value-from-transaction-files#comment-5fb399553923270a49c81415) confirms that `zeroValueInvoice` should be net zero value. We also …
> Bill run summary net zero value fix

- app/presenters/view_bill_run.presenter.js
- app/services/view_bill_run.service.js
- test/services/view_bill_run.service.test.js
https://trello.com/c/kU8RWnKq
https://trello.com/c/TvlmPtZ4
This change updates the properties included in the view bill run response
- `transactionReference` now exists and is set when a bill run is 'sent'
- `debitLineCount`, `debitLineValue`, `creditLineCount`, `creditLineValue`, and `zeroLineCount` can all be removed. We have confirmed with WRLS they are not being used and they were really only intended for our internal use anyway
> Update the view bill run response

- app/controllers/presroc/bill_runs.controller.js
- app/services/delete_bill_run.service.js
- test/controllers/presroc/bill_runs.controller.test.js
- test/services/delete_bill_run.service.test.js
https://trello.com/c/IKn83UpO/1927-s-develop-delete-bill-run-v2
The last part of developing Delete Bill Run is to connect `DeleteBillRunService` to the `DELETE /v2/{regimeId}/bill-runs/{billRunId}` endpoint.
Note that this PR removes the bill run status validation previously done by the service -- we realised during testing that `FetchAndValidateBillRunInvoiceService` already handles status validation prior to the controller actually being called, and therefore additional validation wasn't necessary.
> Connect Delete Bill Run service to endpoint

- app/services/create_minimum_charge_adjustment.service.js
- test/services/create_minimum_charge_adjustment.service.test.js
https://trello.com/c/sNDQVgoh
When testing the 'minimum charge' functionality in the service it was spotted there are 2 issues with the transactions we generate
- The `lineDescription` is supposed to be set to a specific value
- `areaCode` is not being populated
This change fixes both those issues
> Fix incorrect values on minimum charge transaction

- app/services/show_transaction.service.js
- test/services/show_transaction.service.test.js
To support testing our QA @anwarisse1 has asked if the calculated `InvoiceModel` property `$transactionType()` can be included in the test view of a transaction.
This change makes it so 😁
> Add transaction type to test GET endpoint

- app/models/invoice.model.js
- app/services/generate_bill_run.service.js
- test/models/invoice.model.test.js
- test/services/generate_bill_run.service.test.js
- test/services/view_bill_run.service.test.js
It was discovered that deminimis was not being correctly applied in some scenarios involving minimum charge, eg:
- Debit subject to minimum charge with charge value of 1 is added to an invoice.
- Credit with charge value of 2500 is added to the same invoice so the total value of the invoice is 2499.
- The bill run is generated.
- The debit value of the invoice is therefore adjusted to 2500 so the total value of the bill run is now 0.
Since this falls into deminimis, the invoice should not be included in the bill run. However we were not including invoices with minimum charge values when determining whether an invoice was subject to deminimis and therefore the invoice would be included. This change resolves this by amending `InvoiceModel` to no longer exclude minimum charge invoices from …
> Fix deminimis/minimum charge defect

- app/plugins/stop.plugin.js
Since adding the [stop (SIGTERM) plugin](https://github.com/DEFRA/sroc-charging-module-api/pull/105) we see the following warning message in our test suite output
```
(node:1310) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:1310) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```
After looking into it we know it's because every time we generate an instance of the `server` in our test suite (controller tests being the primary culprit) the plugin is being run and a listener added using `process.on('SIGTERM', stop)`. In the context of the test suite we never …
> Fix MaxListenersExceededWarning in tests

- app/controllers/presroc/customer_details.controller.js
- test/models/invoice.model.test.js
Whilst working on the codebase recently we have spotted some stray `console.log()` calls, added no doubt as part of some debugging but inadvertently left in.
> Housekeeping - Remove stray console.log() calls

- test/support/helpers/licence.helper.js
We will need the ability to set initial values of 'tally' fields for licences when testing. This is to support testing we'll be doing as we move from a 'find or insert' pattern to one that uses [UPSERT (on conflict)](https://www.postgresql.org/docs/current/sql-insert.html).
This change expands what we can set in the `LicenceHelper`.
> Add more data overrides to test LicenceHelper

- .github/workflows/ci.yml
We have started seeing PR's raised by [Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) fail because the `Analyze with SonarCloud` step fails.
```
[...]
RULES_SERVICE_TIMEOUT: 1000
GITHUB_TOKEN: ***
SONAR_TOKEN:
/usr/bin/docker run --name e4a97565f2b5d944e48e47caefd7a85a14_7b8529 --label 5588e4 --workdir /github/workspace --rm -e ADMIN_CLIENT_ID -e AIRBRAKE_HOST -e AIRBRAKE_KEY -e PORT -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_HOST -e POSTGRES_PORT -e POSTGRES_DB -e POSTGRES_DB_TEST -e ENVIRONMENT -e RULES_SERVICE_URL -e RULES_SERVICE_USER -e RULES_SERVICE_PASSWORD -e CFD_APP -e CFD_RULESET -e WML_APP -e WML_RULESET -e PAS_APP -e PAS_RULESET -e WRLS_APP -e WRLS_RULESET -e WRLS_SROC_APP -e WRLS_SROC_RULESET -e RULES_SERVICE_TIMEOUT -e …
```
> Fix no SONAR_TOKEN for dependabot PR's

- app/services/create_transaction_bill_run.service.js
- app/services/create_transaction_invoice.service.js
- app/services/create_transaction_licence.service.js
- app/services/create_transaction_tally.service.js
- test/services/create_transaction_tally.service.test.js
https://trello.com/c/1cZkVwM1
In order to use a PostgreSQL `UPSERT` command, we are going to need to build our own SQL statement. An `UPSERT` statement is
```
INSERT INTO invoices ([field names]) VALUES ([values to be inserted])
ON CONFLICT ([constraint field names]) DO UPDATE
SET [field name] = EXCLUDED.[field name]
```
Basically, we are going to need to create both an 'INSERT' and an 'UPDATE' query. In our case what we are inserting or updating is based on the transaction. Is it a credit or a debit? Is it zero value? Is it subject to minimum charge?
Our current design assumes we'll be patching the invoice and licence records and we use the `CreateTransactionTallyService` to generate the 'patch'. This change builds (explodes!) on the existing functionality in the service to also handle …
> Update CreateTransactionTallyService for UPSERT

- app/controllers/presroc/bill_runs.controller.js
- app/services/send_bill_run_reference.service.js
- app/services/send_file_to_s3.service.js
- app/services/send_transaction_file.service.js
- test/services/send_bill_run_reference.service.test.js
- test/services/send_file_to_s3.service.test.js
https://trello.com/c/NfozGoQ6
We have spotted an issue in how the `SendBillRunReferenceService` is interacting with the `SendTransactionFileService` service via the `BillRunsController` `send()` action.
The `SendTransactionFileService` because the instance of bill run it is seeing doesn't have a status of `pending`. With this change we ensure the service will see an updated version of the bill run with the correct status.
> Fix send bill run link to generate file issue

- Dockerfile
We encountered an issue where we were unable to run `npm install` to refresh dependencies in our local container. We tracked this down to the fact that we were enforcing the `node` non-root user for all environments. To resolve this, we've changed `Dockerfile` so that this user is only enforced in production, allowing us to do root user stuff in our local dev environment.
While updating `Dockerfile` we also noticed that the LTS version of Node is now 14, whereas before we were on Node 12. After checking that our unit tests all pass in the new version, we've updated it accordingly.
> Fix Docker local permissions and bump Node version

- .vscode/tasks.json
- db/migrations/20210215154015_alter_transactions_and_invoices.js
- package.json
Working with the API in Docker has been awesome. But we have found there are few things that could make our lives easier
- being able to properly scratch and rebuild the image and environment
- being able to reset the database
The first one especially highlighted an incorrect assumption we had made. We assumed that deleting the image meant it was rebuilt from scratch the next time we ran `docker-compose up`. In fact, we found it was reusing cached layers because as far as it could see nothing had changed.
These changes give us a couple more VSCode tasks to allow us to rebuild the environment properly, or just refresh the DB for those times we want to reset the data.
> Add new docker helpers for local development

- hooks/build
Whilst working with our Docker setup recently we stumbled upon an incorrect assumption we had made. We assumed that when we deleted our image locally Docker was rebuilding the new one from scratch.
In fact, where possible it was using previously cached layers to speed up the build time. This was specifically noticed regards our attempt to always use the latest version of NPM.
We have the command `RUN npm i npm@latest -g` near the start of our Dockerfile. We assumed this meant every time we built Docker was installing the latest version of NPM. In fact, it was just using a previously cached layer.
Having checked the DockerHub logs it looks like we are ok and it is always building from scratch. But as we have done with our [VSCode rebuild …
> Add --no-cache arg to DockerHub build

- .github/workflows/ci.yml
- Dockerfile
To support sending files to AWS S3 we recently added a [Send File To S3 service](https://github.com/DEFRA/sroc-charging-module-api/pull/293). As part of that change, we added `@aws-sdk/client-s3` as a dependency.
Unfortunately, we got hit with 2 things at once. `client-s3` has a dependency on a middleware package that has a **peer** dependency on `react-native`.
Also, npm v7 is out and that automatically installs peer dependencies, even when not really needed.
Until https://github.com/aws/aws-sdk-js-v3/pull/2108 is merged it looks like the workaround is to use the command [`npm install --legacy-peer-deps`](https://github.com/aws/aws-sdk-js-v3/issues/2150#issuecomment-803509600). This tells npm to use pre-v7 behaviours and not automatically install peer dependencies.
> Fix installing react-native as a dependency

- app/presenters/view_bill_run_invoice.presenter.js
- app/presenters/view_invoice.presenter.js
- test/presenters/view_bill.presenter.test.js
- test/presenters/view_invoice.presenter.test.js
https://trello.com/c/TvlmPtZ4
https://trello.com/c/qldEb08U
Recently we [Removed tally fields from invoices in view bill run](https://github.com/DEFRA/sroc-charging-module-api/pull/313) and from [invoices in view /invoices](https://github.com/DEFRA/sroc-charging-module-api/pull/306).
We had confirmed this with the WRLS team, but an overlooked piece of functionality has been highlighted in recent testing which relies on them.
For annual and two-part tariff bill runs all the underlying invoices are all debits. So, in their UI they don't bother showing the breakdown. But for supplementary bill runs, invoices (we should probably use a more generic name 😁) can have a mix of credit and debit lines. So, in their UI they _do_ like to show the breakdown.
> [..] Bills in a supplementary run can …
> Add credit and debit line values back to invoices

- app/services/delete_file.service.js
- app/services/generate_transaction_file.service.js
- app/services/send_file_to_s3.service.js
- app/services/send_transaction_file.service.js
- test/services/delete_file.service.test.js
- test/services/generate_transaction_file.service.test.js
- test/services/send_file_to_s3.service.test.js
- test/services/send_transaction_file.service.test.js
After discovering an issue with uncaught errors during the process of sending a transaction file, we reviewed the error handling and decided to make a change.
Previously, `SendTransactionFileService` was receiving the `notify` server method (which we use for Airbrake logging) and passing it to each of the services it called: `GenerateTransactionFileService` and `SendFileToS3Service`. We did this because the services were intended to run in the background so we wanted to ensure that any issues during the process of generating and sending files were logged using Airbrake instead of disappearing into the ether.
On reflection, we decided it would be better for these services to throw errors, and for `SendTransactionFileService` to be responsible for catching these and logging them using …
> SendTransactionFileService error handling

- app/services/send_transaction_file.service.js
- test/services/send_transaction_file.service.test.js
https://trello.com/c/NfozGoQ6
We overlooked when we completed the [Send File To S3 service](https://github.com/DEFRA/sroc-charging-module-api/pull/293) that we were sending notifications to Errbit that contained unique error messages, for example, `Error sending file /tmp/nalai50003.dat to bucket file-uploads-pre-sroc-service-gov-uk`.
The reason we avoid using unique errors messages to so [Errbit](https://github.com/errbit/errbit) can group the same errors. It has the concept of unique errors, with multiple reported instances. If our error messages are unique it leads to multiple 'error' in Errbit all with a single reported instance.
This can make it difficult to track, triage and prioritise errors. So, this change updates what we pass to the notification to make the errors standard but …
> Fix unique error messages in Send Trans. file

- app/lib/index.js
- app/lib/notifier.js
- app/plugins/index.js
- app/plugins/notifier.plugin.js
- server.js
- test/features/add_notifier_to_requests.test.js
- test/lib/notifier.test.js
- test/support/helpers/route.helper.js
Recently, we added support for sending files to AWS S3. This task will be done in the background, whilst the API ensures a response is sent to the client.
Should the process fail, we still want to see an error logged in Errbit. So, we also ensured the service was able to do this. In review, we also agreed it would be useful to see any errors recorded in the log. For this, the service would also need access to the `logger`, for example, as used by `GenerateBillRunService`.
We then had another thought; wouldn't it be nice if we could see bill run timings recorded in Errbit!? 😁
This has all coalesced into the idea that what we really need is something that makes logging and sending notifications to Errbit accessible in one place.
So, behold the **Notifier** plugin which aims to do just that! …
> Add new Notifier plugin

- app/services/index.js
- app/services/streams/stream_readable_data.service.js
- app/services/streams/stream_readable_records.service.js
- app/services/streams/stream_transform_csv.service.js
- app/services/streams/stream_transform_using_presenter.service.js
- app/services/streams/stream_writable_file.service.js
- package-lock.json
- package.json
- test/services/streams/stream_readable_data.service.test.js
- test/services/streams/stream_readable_records.service.test.js
- test/services/streams/stream_transform_csv.service.test.js
- test/services/streams/stream_transform_using_presenter.service.test.js
- test/services/streams/stream_writable_file.service.js
- test/support/helpers/index.js
- test/support/helpers/stream.helper.js
https://trello.com/c/hyWyM8RL/1940-m-develop-include-required-content-in-transaction-files-v2
The first thing to pull from the [dev spike branch](https://github.com/DEFRA/sroc-charging-module-api/pull/325) are the stream services, which each return an instance of the required stream.
This PR implements the following streams:
- `StreamReadableDataService`: This is invoked with an array of data and returns a `Readable` stream that streams the array one element at a time. It is intended for use when writing a single line of data to a file, eg. header line.
- `StreamReadableRecordsService`: This is invoked with an Objection `QueryBuilder` object and returns a `Readable` stream that streams the results one row at a time.
- `StreamTransformUsingPresenterService`: This is invoked with a …
> Implement stream services for generating transaction files

- app/presenters/base.presenter.js
- app/presenters/index.js
- app/presenters/transaction_file_body.presenter.js
- app/presenters/transaction_file_head.presenter.js
- app/presenters/transaction_file_header.presenter.js
- app/presenters/transaction_file_tail.presenter.js
- test/presenters/base.presenter.test.js
- test/presenters/transaction_file_body.presenter.test.js
- test/presenters/transaction_file_header.presenter.test.js
- test/presenters/transaction_file_tail.presenter.test.js
https://trello.com/c/hyWyM8RL/1940-m-develop-include-required-content-in-transaction-files-v2
The next thing to pull from the [dev spike branch](https://github.com/DEFRA/sroc-charging-module-api/pull/325) are the presenters, which we will use to present data in the format required for the transaction files.
This change introduces 3 presenters:
- `TransactionFileHeadPresenter`
- `TransactionFileBodyPresenter`
- `TransactionFileTailPresenter`
It also adds `_formatDate` and `_leftPadZeroes` methods to `BasePresenter`.
> Presenters for writing transaction file

- app/services/index.js
- app/services/transform_records_to_file.service.js
- test/services/transform_records_to_file.service.test.js
https://trello.com/c/hyWyM8RL/1940-m-develop-include-required-content-in-transaction-files-v2
The next thing to pull from the [dev spike branch](https://github.com/DEFRA/sroc-charging-module-api/pull/325) is the `TransformRecordsToFileService`, which takes an Objection query and passes it through the provided presenters in order to produce a file.
> Transform Records to File service

- app/services/generate_customer_file.service.js
- app/services/index.js
- test/services/generate_customer_file.service.test.js
https://trello.com/c/CSrOSDTP/1942-s-develop-generate-customer-files-v2
This change is the first stage of developing Generate Customer Files, which is the initial `GenerateCustomerFileService` which creates dummy files. We set it up with dummy presenters within the service instead of using `JsonPresenter` (for example) to ensure that the output file remains small and easily testable.
> Create initial Generate Customer File Service

- .github/workflows/ci.yml
In [PR #292](https://github.com/DEFRA/sroc-charging-module-api/pull/292) we attempted to work around an issue with Dependabot builds failing because the SonarCloud token was missing.
As part of the change, we learnt that it was actually just to do with a change by GitHub about where the token now needs to be stored. We left the workaround in because we believed it would be a good fallback should the token be missing.
Since then though we have seen every Dependabot PR still fail because the token is flagged as missing. The CI check passes but the SonarCloud step is left unresolved because we skip it. But we know having the token in the right place works on all our other projects.
This has led us to believe that our check for a token is always returning false so the SonarCloud step is never …
> Revert Dependabot SonarCloud workaround

- app/controllers/admin/test/test_bill_runs.controller.js
- app/controllers/presroc/bill_runs.controller.js
- app/services/generate_bill_run.service.js
- app/services/send_transaction_file.service.js
- test/services/generate_bill_run.service.test.js
- test/services/send_transaction_file.service.test.js
- test/support/generators/bill_run.generator.js
In [Add new Notifier plugin](https://github.com/DEFRA/sroc-charging-module-api/pull/324) we created a new class to be used by services for recording logs entries and sending notifications to Errbit.
It is intended to unify our notifications plus make them available to all services via the [Hapi request](https://hapi.dev/api/?v=20.1.2#request) object.
This change covers switching our existing log and airbrake uses to use the `Notifier` instance instead.
> Switch to using Notifier plugin

- app/lib/notifier.js
- app/plugins/notifier.plugin.js
- test/lib/notifier.test.js
Each [Hapi request](https://hapi.dev/api/?v=20.1.2#request) is assigned a unique ID that is a mix of actual details about the host and environment plus unique values.
For example, when running the service locally using Docker an ID will look like `1617652737349:533c1e381364:1315:kn50o8hf:10000`.
Currently, we assume the link between our log or error messages and the logged request based on context and timing. But if the `Notifier` instance we add to the request is aware of the request ID, it can ensure this is always included so we can be certain what links with what.
This change ensures whenever `Notifier` is used it includes the request ID in the output.
> Add Hapi request ID to Notifier

- app/presenters/view_transaction.presenter.js
- app/services/view_bill_run_invoice.service.js
- db/migrations/20210406075137_alter_transactions.js
- test/presenters/view_invoice.presenter.test.js
- test/presenters/view_transaction.presenter.test.js
We added a status field to the transaction based on [V1 of the API](https://github.com/DEFRA/charging-module-api) right back at the start of V2.
However, as we have iterated we have ensured that the bill run status is the primary indicator for it and all things linked to it. We have now had confirmation from the WRLS team that the status field on the transaction _is_ ignored (currently displayed in `GET /invoices/{id}`).
So, this change is about removing the defunct field.
> Remove transaction level status

- .vscode/tasks.json
- README.md
The recent PR [Add new docker helpers for local development](https://github.com/DEFRA/sroc-charging-module-api/pull/314) expanded the number of tasks we have in our VSCode tasks file.
On reflection, we felt that there were now commands not being used, or we were always running the same set of tasks. So, the first part of this change covers unifying some of the tasks, especially those that allow for repeated running.
The second part is being able to clearly distinguish the tasks when displayed in the list. Shorter commands that have a more direct link to what underlying command they are running we felt would help improve the understanding and use of the tasks.
<details>
<summary>Before screenshot</summary>
</details>
<details>
<summary>After screenshot</summary>
</details>
> Simplify the VSCode tasks

- test/controllers/admin/test/test_bill_runs.controller.test.js
- test/support/helpers/general.helper.js
A small bit of housekeeping. We recently made a change where we thought we might also need to use the `sleep()` method in another test. So, we refactored it to the `GeneralHelper` where it makes better sense to be.
Turns out we didn't need it but we still feel there is value in this minor bit of housekeeping. Hence the change.
> Move test sleep() method to GeneralHelper

- app/controllers/presroc/bill_runs_invoices.controller.js
https://trello.com/c/IYJIYLSB
> This is a similar change as [Fix - Move delete bill run to background task](https://github.com/DEFRA/sroc-charging-module-api/pull/343)
It was found during testing that when we have large invoices it takes a long time for the service to respond.
We have imposed a requirement that all of the API's endpoints should respond in 1 second or less (on average) and this falls outside that if the invoice is too large. This change tweaks the delete invoice endpoint so that sends an immediate 204 response if the invoice can be deleted, and then does the actual deletion in the background.
> Fix - Move delete invoice to background task

- app/presenters/customer_file_body.presenter.js
- app/presenters/customer_file_head.presenter.js
- app/presenters/customer_file_tail.presenter.js
- app/presenters/index.js
- test/presenters/customer_file_body.presenter.test.js
- test/presenters/customer_file_head.presenter.test.js
- test/presenters/customer_file_tail.presenter.test.js
- test/presenters/transaction_file_body.presenter.test.js
- test/presenters/transaction_file_head.presenter.test.js
- test/presenters/transaction_file_tail.presenter.test.js
- test/support/helpers/index.js
- test/support/helpers/presenter.helper.js
https://trello.com/c/CSrOSDTP/1942-s-develop-generate-customer-files-v2
This branch creates presenters which will transform data in the customer table into the format required for customer files.
It also introduces `PresenterHelper` with a `generateNumberedColumns` method which can be used to generate the arrays of column names (eg. `['col01', 'col02', 'col03']` used in all of the file presenter tests, and refactors the existing transaction file tests to use it.
> Presenters for writing customer files

- app/controllers/presroc/bill_runs.controller.js
- test/controllers/presroc/bill_runs.controller.test.js
https://trello.com/c/CSrOSDTP/1942-s-develop-generate-customer-files-v2
When we send a bill run, we also want to generate and send a customer file if one is required. This change adds the `SendCustomerFileService` to the 'send bill run' controller in order to achieve this.
> Generate customer files when sending bill runs

- app/services/send_customer_file.service.js
- test/services/send_customer_file.service.test.js
https://trello.com/c/CSrOSDTP/1942-s-develop-generate-customer-files-v2
After merging the individual parts, we realised that `SendCustomerFileService` wasn't passing the correct parameters to `GenerateCustomerFileService` -- it was passing a regime object instead of the regime id, and it wasn't providing the file reference needed in the transaction file. This PR fixes both of these issues.
> Pass correct params to GenerateCustomerFileService

- app/services/generate_customer_file.service.js
- test/services/generate_customer_file.service.test.js
https://trello.com/c/21HaVqbi/1934-m-include-required-content-in-customer-files-v2
AC5 specifies that customer files should be sorted by order of customer reference. This change implements this.
> Customer file is sorted by customer reference

- app/controllers/presroc/bill_runs_invoices.controller.js
- app/services/delete_invoice.service.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
- test/services/delete_invoice.service.test.js
After we [moved delete invoice to a background task](https://github.com/DEFRA/sroc-charging-module-api/pull/345), we found that trying to delete a non-existent invoice, or an invoice not connected to the given bill run, would bring the service down. This turned out to be caused by `FetchAndValidateBillRunInvoiceService` throwing an error in these circumstances -- moving the delete invoice task to the background meant that there was nothing to catch these errors.
In order to resolve this, we have moved `FetchAndValidateBillRunInvoiceService` into the controller, so that a `404` or `409` error will be presented to the user if it occurs. We have also amended `DeleteInvoiceService` to use the notifier to log any additional errors which may occur so that they don't bring down the service.
> Delete invoice error handling

- app/controllers/presroc/bill_runs.controller.js
- app/services/delete_bill_run.service.js
- app/services/delete_invoice.service.js
- app/services/send_customer_file.service.js
- app/services/send_transaction_file.service.js
- test/services/delete_bill_run.service.test.js
After [moving delete bill run to a background task](https://github.com/DEFRA/sroc-charging-module-api/pull/343), this adds error trapping using `notifier` to ensure that any unexpected errors don't bring down the service.
This isn't being done as part of a defect, as all necessary bill run validation (eg. checking the bill run exists and can be edited) is handled prior to calling the service; however while [adding error handling to delete invoice](https://github.com/DEFRA/sroc-charging-module-api/pull/356) we realised we should always be using `notifier` within services intended to run in the background.
While doing this, we noticed that a few comments for other "background" services were either missing or incorrect (eg. specifying that `notifier` is optional); these have also been …
> Delete bill run error handling

- app/services/create_customer_details.service.js
- db/migrations/20210413154851_alter_customers.js
- test/services/create_customer_details.service.test.js
- test/services/send_customer_file.service.test.js
https://trello.com/c/21HaVqbi/1934-m-include-required-content-in-customer-files-v2
AC7 states that existing detail records for a customer reference should be overwritten if a new one is added. We therefore change `CreateCustomerDetailsService` to use an upsert-style query when adding records by adding a unique constraint to the `customer_reference` field, and adding `.onConflict('customerReference').merge()` when we `insert`.
> Overwrite existing customer details entry

- app/presenters/transaction_file_body.presenter.js
- app/services/generate_transaction_file.service.js
- test/presenters/transaction_file_body.presenter.test.js
https://trello.com/c/RBEmt0JV/1924-include-required-content-in-transaction-files-v2
Certain fields in the transaction file are only populated depending on whether or not the transaction is a compensation charge. We found during testing that this was not being done correctly. This turned out to be because the compensation charge is stored in generic field `regimeValue17` which is stored as a string, not a boolean, and therefore was always determined to be `true` regardless of whether it was the string `'true'` or `'false'`. We fix this by adding a helper method to correctly parse this field, and amend the existing `_blankIfCompensationChargeOrMinimumCharge` and `_blankIfNotCompensationCharge` methods to use this instead of `regimeValue17`.
This led to our `GenerateTransactionFileService` …
> Fix transaction file compensation charge defect

- app/translators/calculate_charge.translator.js
- test/translators/calculate_charge.translator.test.js
During transaction file testing we found that prorata days were not being correctly formatted for two-part tariffs; the acceptance criteria state that a two-part tariff should have the string `000/000` for prorata days but this was not being done.
This fix resolves this by amending the calculate charge translator so that two-part tariffs store `000/000` for the prorata days.
> Correctly record prorata days for two-part tariffs

- app/presenters/transaction_file_body.presenter.js
- test/presenters/transaction_file_body.presenter.test.js
Our [fix for the transaction file compensation charge defect](https://github.com/DEFRA/sroc-charging-module-api/pull/360) was found to cause issues for bill runs with minimum charge transactions. This turned out to be because `regimeValue17` is stored as `null` for minimum charges, thus causing an error when we attempt to make it lower case. Adding the optional chaining operator to our `_compensationCharge` method means we now return `false` without issue if `regimeValue17` is `null`.
This defect was undiscovered in unit test as our test incorrectly stated `regimeValue17` would be `'false'` for a minimum charge adjustment. The test has been amended accordingly.
> Fix transaction file minimum charge defect

- db/migrations/20210416132011_create_customer_files.js
This change creates the `customer_files` table. It differs slightly from the v1 table, in that we don't record the status -- we may adjust this in future but for now we work on the assumption that files are only added to the db after being successfully generated and sent (whereas v1 adds them with an `initialised` status, changing to `exported` once they are generated and sent).
> Create customer files table

- db/migrations/20210416143924_alter_customers.js
This change creates a `customer_file_id` column in the `customers` table which references the `id` column in the `customers` table.
> Link customers table to customer_files

- app/models/customer.model.js
- app/models/customer_file.model.js
- app/models/regime.model.js
This change creates `CustomerFileModel`, and creates relationships between it,`CustomerModel` and `RegimeModel`.
> Create customer file model

- app/services/send_customer_file.service.js
- test/services/send_customer_file.service.test.js
We discovered a bug in `SendCustomerFileService` which was affecting the generation of multiple files. Say for example regions `A`, `B` and `W` had customer changes; when `SendCustomerFileService` was called with the array of all regions `['A', 'B', 'E', 'N', 'S', 'T', 'W', 'Y']`, files would be created for regions `A` and `B` but not for region `W`.
We found that this was caused by the loop which iterates over each region; when a file was not needed for a region, we would `break` which it turns out was incorrect -- this would break out of the loop entirely so it would only produce files up until the first one that wasn't needed. 
To fix this, we changed `break` to `continue`, which will correctly loop back and continue with the next region.
> Fix multiple region customer file generation

- db/migrations/20210420141638_create_exported_customers.js
Once a customer change is exported, we want to delete the customer's details as per the [acceptance criteria](https://trello.com/c/yw0K7fge/244-generate-customer-files) but retain a record that their details were updated. The `exported_customers` table created in this PR will hold this record by saving `customer_reference` alongside `customer_files.id` of the customer file that the details change was included in.
> Create exported_customers table

- app/controllers/presroc/customer_details.controller.js
- test/controllers/presroc/customer_details.controller.test.js
We have just spotted that the response code when a customer change is posted to `/v2/wrls/customer-changes` is `204`. Our convention is to use `201` for our `POST` endpoints as we are creating new records.
This is a fault of the [Swagger docs](https://app.swaggerhub.com/apis-docs/sro/sroc-charging-module-api/draft) which also say the response will be a 204 no doubt because we copy and pasted them from the V1 docs!
> Fix POST /customer-changes response code

- app/services/send_customer_file.service.js
- test/services/send_customer_file.service.test.js
https://trello.com/c/Nu0BAjJE
Whilst looking to [Add generate customer file task](https://github.com/DEFRA/sroc-charging-module-api/pull/370) we came across some odd behaviour.
We are working on a new `TaskNotifier` intended for use outside of a Hapi request. To confirm it was working as expected we introduced an error into the `SendCustomerFileService` as it processed each regime. So, we should have seen 4 errors reported to Errbit but we only saw 1.
After much (_much_ 😩) digging we tracked down the problem. Airbrake runs each 'notification' through a series of filters before deciding whether to forward it on. We were falling foul of a check which looks to see if the same error has been reported in the last 1000ms. In our case it had.
```javascript
let s = JSON.stringify(notice.errors); …
```
> Fix SendCustomerFileService error logging

- app/models/index.js
- app/services/send_customer_file.service.js
- db/migrations/20210421110628_alter_customer_files.js
- test/services/send_customer_file.service.test.js
When generation of a customer file is initiated, we want to add a record of the file to the `customer_files` table with a default status of `initialised`, then set the status to `pending` once file generation begins. If file generation is successful then we set the status to `exported` and set `export_date` to the current date/time.
This change adds `status` and `export_date` columns to the `customer_files` table, and updates the send customer file process to populate the table accordingly.
Note that this change does not yet include additional validation to ensure that the customer file isn't already being generated; this will be added in a future PR.
> Add customer file to customer_file table

- app/services/db_errors.service.js
- test/services/db_errors.service.test.js
Client systems when adding transactions can include a `clientId` property. This can be whatever they like, as long as it's unique for transactions in that regime. It's intended to be used for the client system to include _their_ transaction ID so they can ensure they don't accidentally duplicate a charge.
This was something we added into [V1 of the API](https://github.com/charging-module-api) to give client systems more confidence when re-trying failed transaction entries. In V1 it was completely custom and relied on us querying the DB first for a matching transaction. If found we then sent our own custom response.
```json
{
"id": "5ee921b3-3ab2-45ea-98b4-7d82ece0267a",
"clientId": "1234567890"
}
```
In V2 we no longer query for a matching transaction first. Instead, we rely on a DB …
> Fix - add client ID back into conflict response

- app/models/exported_customer.model.js
- app/models/index.js
- app/services/index.js
- app/services/move_customers_to_exported_table.service.js
- test/services/move_customers_to_exported_table.service.test.js
This service moves customers for a given regime and region from the `customers` table to the `exported_customers` table:
- It creates an entry in the `exported_customers` table for each customer, adding the `customer_reference` (the only detail we need to record) alongside the id of the customer file they were exported in;
- It deletes the corresponding entries from the `customers` file.
> Move Customers To Exported Table service

- app/tasks/customer_files.task.js
- app/tasks/index.js
- app/tasks/task_runner.js
- package.json
- test/tasks/customer_files.task.test.js
- test/tasks/task_runner.test.js
https://trello.com/c/Nu0BAjJE
Client systems can send us changes to customer details which we then send across to SOP. Customers changes are grouped by region and if a bill run with a matching region is `sent` we also generate that customer file.
But if there happens to be no bill runs for a region that week, the business still wants us to ensure the customer changes are sent to SOP. We do that by triggering the creation of the customer files on a schedule once a week. The plan is for a Jenkins job to be set up to run on a schedule and use this task we are adding to do that.
This is the first for the service; a 'service' that is called outside of a request (in this case from `package.json`). To be consistent with the ECS naming convention and what we have done in Jenkins for our migrate …
> Add generate customer file task

- app/tasks/task_runner.js
When we added the [customer file task](https://github.com/DEFRA/sroc-charging-module-api/pull/370) we included a temporary implementation for a 'notifier because we knew [Add TaskNotifier and refactor existing Notifier](https://github.com/DEFRA/sroc-charging-module-api/pull/379) was waiting in the wings.
The `TaskNotifier` has now been merged so this change updates the `TaskRunner` to use it.
> Update TaskRunner to use TaskNotifier

- app/controllers/admin/test/test_customer_files.controller.js
- app/controllers/index.js
- app/routes/test.routes.js
- app/services/index.js
- app/services/list_customer_files.service.js
- test/controllers/admin/test/test_customer_files.controller.test.js
- test/services/list_customer_files.service.test.js
- test/support/helpers/customer.helper.js
- test/support/helpers/index.js
https://trello.com/c/h5nxl1FS
In [V1 of the API](https://github.com/DEFRA/charging-module-api) an endpoint had been provided that allowed the QA team to see the customer file audit records.
They'd like the same endpoint in V2 so this change adds it.
There will be some changes though
- like the `GET /admin` regimes and authorised systems endpoints, and the `GET /admin/test/transactions` endpoint we intend to just return the data raw
- like those endpoints, there will be no filtering (certainly in this initial version)
- like those endpoints we'll include any child records automatically
> Add customer files test endpoint

- app/services/generate_customer_file.service.js
- app/services/send_customer_file.service.js
- test/services/generate_customer_file.service.test.js
- test/services/send_customer_file.service.test.js
During testing we found that if a customer file was successfully generated but sending failed (eg. an invalid bucket is specified), the customer records in that file would be incorrectly included in the next customer file. This change prevents this happening:
- Once a customer file record is created, we patch the customer changes for that regime and region so that `customer_file_id` equals the id of the created record, ensuring we do not overwrite the file id if it already exists for a customer change;
- When we generate the file, we only select customer changes that have the correct `customer_file_id`.
This is implemented by refactoring `GenerateCustomerFileService` so that we pass the instance of `CustomerFileModel` to it, which it uses to get the id (plus other things needed for the …
> Fix previous changes in customer file export

- app/controllers/admin/test/test_customer_files.controller.js
- app/models/customer_file.model.js
- app/models/exported_customer.model.js
- app/models/sequence_counter.model.js
- app/routes/test.routes.js
- app/services/index.js
- app/services/show_customer_file.service.js
- test/controllers/admin/test/test_customer_files.controller.test.js
- test/services/show_customer_file.service.test.js
- test/support/helpers/customer.helper.js
[Add customer files test endpoint](https://github.com/DEFRA/sroc-charging-module-api/pull/381) enables listing all customer files for a regime. But each customer file is linked to a set of `exported_customers` and there is currently no way to view them.
This change adds an endpoint that allows our test team to see the detail linked to a `customer file`.
** Note, we have essentially used the same blueprint of List and Show as used for `regime` and `authorised_systems`.
> Add test Show customer file endpoint

- test/services/move_customers_to_exported_table.service.test.js
We found that the tests for `MoveCustomersToExportedTableService` would very occasionally fail. On closer examination, it looked like there was a missing `await` in the test setup which was probably causing a situation where customer details weren't in place ready for test, which would subsequently fail. This change hopes to fix this!
> Fix failing MoveCustomersToExportedTableService tests

- test/services/plugins/db_errors.service.test.js
- test/services/plugins/object_cleaning.service.test.js
- test/services/plugins/request_bill_run.service.test.js
We have started to move our services into folders that reflect their purpose. [A recent change](https://github.com/DEFRA/sroc-charging-module-api/pull/389) moved plugins into their own `plugins` folder; this PR moves their tests into a similar folder.
> Move plugin test files to plugins folder

- app/plugins/index.js
- app/plugins/request_invoice.plugin.js
- app/services/index.js
- app/services/plugins/request_invoice.service.js
- server.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
- test/features/find_validate_invoices.test.js
- test/services/plugins/request_invoice.service.test.js
- test/support/helpers/route.helper.js
This change introduces `RequestInvoicePlugin` (similar to the existing bill run plugin) which will check requests to see if they contain `/invoices/`, retrieving the invoice if it exists or throwing a `404` error if it doesn't.
> Create plugin to add invoice to request when needed

- .vscode/tasks.json
The recent change to [Use consistent naming convention package scripts](https://github.com/DEFRA/sroc-charging-module-api/pull/388) unfortunately omitted some updates in the VSCode tasks file.
This change fixes the omission.
> Fix DB rebuild vscode task

- app/services/plugins/request_bill_run.service.js
Spotted whilst working on ['Create plugin to add invoice to request when needed'](https://github.com/DEFRA/sroc-charging-module-api/pull/393) that we were not using await/async in an optimal way.
This housekeeping change corrects the issue.
> Correct await async usage in RequestBillRunService

- app/models/invoice.model.js
- app/services/index.js
- app/services/invoice_rebilling.service.js
- app/services/invoice_rebilling_create_transaction.service.js
- test/services/invoice_rebilling.service.test.js
- test/services/invoice_rebilling_create_transaction.service.test.js
- test/support/helpers/invoice.helper.js
https://trello.com/c/qkWbpJlf/1962-m-create-re-billing-transactions
This change introduces the `InvoiceRebillingService` which accepts an invoice and will copy its licences and transactions to the supplied cancel invoice (with transaction types swapped so that credits become debits and vice-versa) and rebill invoice.
During development we found that `InvoiceModel` needed to be amended to accommodate `rebilledType` -- this change is included in this PR.
> Create Invoice Rebilling Service

- app/services/invoice_rebilling_validation.service.js
- test/services/invoice_rebilling_validation.service.test.js
When an invoice is rebilled, two rebill invoices are created: the cancel invoice, which cancels out the original invoice, and the rebill invoice, which bills the customer. We have had confirmation that rebill invoices can be rebilled but cancel invoices cannot; this change adds additional validation for this.
> Add rebilling validation for cancel invoices

- app/routes/bill_run_invoice.routes.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
- test/support/helpers/authorised_system.helper.js
https://trello.com/c/sMC4Ns4D
We have recently added the `PATCH /v2/{regimeId}/bill-runs/{billRunId}/invoices/{invoiceId}/rebill` endpoint as part of implementing a new feature that allows for an invoice to be rebilled (cancelled out by one new invoice and regenerated in another).
This work won't be complete before we go live with the rest of our other functionality but the endpoint would currently be available. Though we wouldn't expect our client systems to attempt to use it, just to be sure we are ensuring access to it is only possible by the admin user.
So, this change adds the admin auth scope to the route's options plus any tweaks needed to make this work.
> Add auth scope to invoice rebill endpoint

- app/services/invoice_rebilling_validation.service.js
- test/services/invoice_rebilling_validation.service.test.js
https://trello.com/c/e2Z8puRX/1976-prevent-duplicate-re-billing-of-a-single-invoice
In order to prevent additional rebilling, we need to add validation to check whether it is currently being rebilled. We do this by checking to see if any invoices exist which have the invoice's id in the `rebilled_invoice_id` field.
This also satisfies the criteria that an invoice that has been rebilled can be rebilled again if the previous rebilling has been cancelled; in this scenario, both the cancel invoice and the rebill invoice will have been deleted meaning there won't be any invoices with the id in the `rebilled_invoice_id` field.
> Prevent duplicate billing

- app/presenters/view_invoice.presenter.js
- test/presenters/view_invoice.presenter.test.js
https://trello.com/c/3Uugplg1/1970-s-include-re-billing-data-in-view-invoice-response
We add `rebilledType` and `rebilledInvoiceId` to `ViewInvoicePresenter` so that rebilling info is present when viewing an invoice.
> Add rebilling info to ViewInvoicePresenter

- .env.example
- config/authentication.config.js
- db/seeds/02_authorised_systems.js
Currently, we support seeding the 'admin' and a 'system' authorised system (user).
What has actually been happening is we have been seeding the 'admin', but using WRLS's credentials as the 'system' user. We're getting close to going live with the service so we need to move away from using WRLS's credentials and use our own system account.
Whilst looking into what accounts we have we noted there is one earmarked for the TCM, though it is no longer our intent to link the 2 systems. This observation came at the same time our test team asked if there was an account they could make changes to as part of their automated testing.
So, this change is all about adding support to seed a 'test' authorised system. But it's also signalling our intent to use our own credentials rather than our clients …
> Add support to seed test authorised system

- app/controllers/admin/authorised_systems.controller.js
- app/routes/authorised_system.routes.js
- app/services/index.js
- app/services/update_authorised_system.service.js
- test/controllers/admin/authorised_systems.controller.test.js
- test/services/update_authorised_system.service.test.js
In [V1 of the API](https://github.com/charging-module-api) there was an endpoint that allowed the admin user to change the details of an 'authorised system' (our name for user accounts!)
We've always had the intention of bringing it into V2, it was just very low on the list of priorities. Now it's been identified as a need by our test team to allow them to automate the testing of authentication and authorisation.
So, this change adds a new update authorised system endpoint which will allow us to
- amend the status of an authorised system
- amend the name of an authorised system
- amend what regimes an authorised system has access to
> Add update (PATCH) authorised systems endpoint

- app/services/view_bill_run.service.js
https://trello.com/c/nHyddqSo/1969-s-include-re-billing-data-in-view-bill-run-response
Alongside adding the rebililng fields to the View Bill Run presenter, we also need to add them to the query that supplies the data for the presenter, which we do in this change.
> Add rebilling fields to View Bill Run query

- app/services/view_bill_run_invoice.service.js
https://trello.com/c/3Uugplg1/1970-s-include-re-billing-data-in-view-invoice-response
Alongside adding the rebilling fields to the View Bill Run Invoice presenter, we also need to add them to the query that supplies the data for the presenter, which we do in this change.
> Add rebilling fields to View Bill Run Invoice query

- app/controllers/admin/bill_runs.controller.js
- app/controllers/index.js
- app/routes/bill_run.routes.js
- app/services/plugins/request_bill_run.service.js
- test/controllers/admin/bill_runs.controller.test.js
- test/services/plugins/request_bill_run.service.test.js
https://trello.com/c/ntPvucIj/1974-enable-admin-endpoint-to-manually-trigger-a-transaction-file-v2
After [initially raising a PR](https://github.com/DEFRA/sroc-charging-module-api/pull/428) to create the endpoint and a stub `AdminSendTransactionFileService`, we realised once we started work on developing the admin service that this wouldn't be necessary -- we can simply call the existing `SendTransactionFileService` from the admin controller. We therefore pulled the review request for the previous PR and raised this one to create the admin endpoint and call `SendTransactionFileService` from within it.
While manually checking the endpoint, we found that the request would be rejected by the `RequestBillRunService` plugin before reaching the controller; this was due to the bill run status …
> Revised Admin Send Transaction File endpoint

- .vscode/tasks.json
- README.md
A little while ago we did some work to [Simplify the VSCode tasks](https://github.com/DEFRA/sroc-charging-module-api/pull/341)
In that change we got the DB setup commands down to 2; one for the main DB and the other for the test DB. Since then  we've come to realise if we need to reset the main DB, it's a given we also need to reset the test DB.
So, this is a small quality of life tweak to continue to try and keep the tasks list as clean and short as possible, and make our daily lives a bit easier. In this change, we merge the DB reset commands into one VSCode task.
> Merge VSCode db setup tasks

- .vscode/tasks.json
- db/drop.database.js
- package.json
When migrations go bad, they go _real_ bad! Sometimes, when working locally our only solution is to drop the whole environment and start again.
As an interim step, we'd like the option of being able to simply 'nuke' the DB. Essentially drop it completely and start again.
This change adds a `package.json` script that will allow us to do that.
> Add nuke-db npm script

- app/controllers/admin/bill_runs.controller.js
- app/services/admin_send_transaction_file.service.js
- test/controllers/admin/bill_runs.controller.test.js
https://trello.com/c/ntPvucIj/1974-enable-admin-endpoint-to-manually-trigger-a-transaction-file-v2
The final stage of changing our admin endpoint to behave syncronously is to update it to use the newly-created `AdminSendTransactionFileService`.
While manually testing we found a small issue with how `AdminSendTransactionFileService` was passing `BoomNotifier` to `SendTransactionFileService` so we resolved this.
> Use admin send transaction file service in endpoint

- app/routes/bill_run_invoice.routes.js
We have been asked to enable rebilling so that WRLS colleagues can start integration testing, which we do in this PR. Note that we intend to revert this to make rebilling inaccessible prior to go-live.
> Remove rebilling endpoint feature flag

- app/translators/customer.translator.js
- db/migrations/20210518115807_create_customers.js
- test/services/create_customer_details.service.test.js
https://trello.com/c/gRWL23rB/1963-validate-customer-change-data-v2
Testing found the following defects, which this PR fixes:
- Customer name accept a maximum of 360 characters but will not accept more than 255; fixed by updating the migration to specify the field length.
- Postcode is not a mandatory field; fixed by making it required in the validation, and added `.notNullable()` to its definition in the migration.
> Fix defects in customer data validation

- app/routes/bill_run.routes.js
- test/controllers/admin/bill_runs.controller.test.js
https://trello.com/c/ntPvucIj
Spotted when working on another change that the admin bill runs `/send` endpoint (intended to re-try sending the transaction file for 'pending' bill runs) is missing the route `options` property, specifically one which sets the auth scope as `admin`.
This change fixes it and the tests.
> Fix missing admin auth scope on bill run /send

- app/plugins/index.js
- app/plugins/request_licence.plugin.js
- app/services/index.js
- app/services/plugins/request_licence.service.js
- server.js
- test/services/plugins/request_licence.service.test.js
https://trello.com/c/q3yaHhS7/1982-remove-transactions-v2-licence-level
We have plugins to retrieve and validate bill runs and invoices whenever an endpoint with `bill-runs` and/or `invoices` is hit. The "delete licence" endpoint is the first `licences` endpoint so we develop a similar `RequestLicence` plugin and service to retrieve and validate the requested licence.
Note that this code is very similar to the existing `RequestBillRun` and `RequestInvoice` services and is therefore a prime candidate for refactoring into a base request service with bill run, invoice and licence services that inherit from it; we will consider this for a future PR.
> Develop Request Licence plugin

- app/plugins/router.plugin.js
- app/routes/bill_run_invoice.routes.js
- app/services/index.js
- app/services/plugins/filter_routes.service.js
- test/services/plugins/filter_routes.service.test.js
https://trello.com/c/sMC4Ns4D
In [Add auth scope to invoice rebill endpoint](https://github.com/DEFRA/sroc-charging-module-api/pull/411) we brought the invoice rebilling endpoint into the `admin` auth scope as a way of controlling access to it because it's not yet finished. We didn't want anyone inadvertently using it before it's ready.
But then in [Remove rebilling endpoint feature flag](https://github.com/DEFRA/sroc-charging-module-api/pull/436) we had to take it off again to allow our client systems to be able to access the endpoint to start their work.
The idea was that we would re-add the scope before go-live, and then take it off again to allow testing. Just writing it down and reading it back we can see that way lies madness!
But then inspiration hit! We just need to _not_ register …
> Add filtered routes service

- app/models/bill_run.model.js
- test/services/create_transaction.service.test.js
- test/support/helpers/bill_run.helper.js
We've spotted an edge case the CM isn't handling. Once a bill run is `generated` we allow 2 kinds of edits
- deleting an invoice
- adding a transaction
Our commitment to client systems is that the invoice and credit note values of a generated bill run are correct. When deleting an invoice, we are able to (and appear to be!) correctly recalculating the invoice and credit note values to reflect the change.
Adding a transaction is harder. What was an invoice could suddenly become a credit note, a zero value transaction, or something even more complicated like minimum charge. Because of this the expectation was that the status would have to go back to `initialised` and the client system would be required to call the `/generate` endpoint again.
A recent test has highlighted we're not doing …
> Fix generated bill run status after add trans.

- app/services/delete_licence.service.js
- app/services/index.js
- test/services/delete_licence.service.test.js
https://trello.com/c/RsNVNpvf/1985-remove-licences-delete-licence-and-transactions
This implements the initial `DeleteLicenceService`, which deletes a licence and its transactions. Note that recalculation of the bill run and invoice (including deleting the invoice if this deletion leaves it without any licences/transactions) will be done in future PRs.
> Develop initial DeleteLicenceService

- app/services/invoice_rebilling_create_transaction.service.js
- test/services/invoice_rebilling_create_transaction.service.test.js
https://trello.com/c/qkWbpJlf
We have a constraint on the `transaction` record to ensure we don't allow 2 transactions with the same `regime_id` and `client_id` to be inserted. This is how client systems have confidence we don't allow duplicate transactions to get into an invoice.
We forgot about this though when adding the rebilling functionality. All our manual and unit testing did not include having an original invoice with transactions with client ID's set.
In recent testing, we found that the copying of transactions from the original to the rebilling invoices fails because of this constraint.
So, this change fixes the issue to ensure we still prevent duplicate transactions from being added but allow us to create rebilling invoices.
> Fix Client ID unique constraint for rebilling

- app/models/bill_run.model.js
- app/services/plugins/request_bill_run.service.js
- test/controllers/presroc/bill_runs.controller.test.js
- test/models/bill_run.model.test.js
- test/services/plugins/request_bill_run.service.test.js
We have faced questions recently about what we should do when amending a bill run that has the status of `approved`. Within the team and after speaking to WRLS we are all agreed that once a bill run is marked as `approved` it should not be possible to make changes to it.
Simply removing the status from `BillBunModel.$editable()` though has knock-on repercussions for `/send` a bill run and `/delete` a bill run, plus `/delete` an invoice.
Having checked the scenarios we are dealing with what we really need is the ability to check
- if a bill run is _patchable_, for example, we can call the `/generate`, `/approve` and `/send` requests on it
- if a bill run is _editable_, for example, we can add a transaction or delete an invoice
This change refactors the existing `$editable()` to remove the …
> Refactor bill run editable and add patchable

- app/models/invoice.model.js
- app/services/calculate_minimum_charge.service.js
- test/services/calculate_minimum_charge.service.test.js
https://trello.com/c/KaBWf4Bh
Whilst undertaking Business Acceptance Testing (BAT) the WRLS spotted that the CM does not calculate minimum charge at the appropriate level.
The scenario they created was
- create a bill run
- for customer `C01` and licence `L01` add a subject to minimum charge transaction for £20
- for the same customer but licence `L02` add a subject to minimum charge transaction for £50
The _expected_ result is that a minimum charge would still be added to bring the total value of licence `L01` up to £25. The _actual_ result was that no minimum charge was applied.
On investigation, we identified the problem. Essentially, we are currently determining which invoices to consider reviewing for minimum charge based on the total value of minimum charge transactions at …
> Fix minimum charge being calculated at wrong level

- app/controllers/presroc/bill_runs_licences.controller.js
- test/controllers/presroc/bill_runs_licences.controller.test.js
https://trello.com/c/ZjWhOdbQ/1984-remove-licences-initial-validation
https://trello.com/c/RsNVNpvf/1985-remove-licences-delete-licence-and-transactions
After implementing the [validate licence](https://github.com/DEFRA/sroc-charging-module-api/pull/445) and [delete licence](https://github.com/DEFRA/sroc-charging-module-api/pull/446) services, we add these to the controller using the established pattern of calling the validation asynchronously so any errors are returned immediately, then calling the deletion synchronously so we can return a `204` response straight away while deletion continues in the background.
Note that at this stage additional work is needed on the delete licence service in order to recalculate bill run and invoice summary info; however this won't affect how we call …
> Add delete licence services to controller

- app/services/invoice_rebilling_initialise.service.js
- test/services/invoice_rebilling_initialise.service.test.js
https://trello.com/c/rPTeXdJO
Spotted during testing that the rebilled invoices created from the original invoice don't have the same deminimis and minimum charge flags set.
This change ensures they are copied over as per the original invoice.
> Fix missing flags on rebill invoices

- app/presenters/view_transaction.presenter.js
- app/services/invoice_rebilling_create_transaction.service.js
- app/services/view_bill_run_invoice.service.js
- db/migrations/20210609165720_alter_transactions.js
- test/presenters/view_transaction.presenter.test.js
- test/services/invoice_rebilling_create_transaction.service.test.js
https://trello.com/c/qkWbpJlf
As part of the rebilling functionality, we record a link between the new rebilled invoices (`C` and `R`) and the original (`O`). We do this by recording the original invoice ID in `invoices.rebilled_invoice_id`.
We have also been asked to record a link between the rebilled transactions and the original transaction. This change adds that ability along with adding it to the `GET /invoice` response so it can be seen by client systems.
> Link rebilled transaction to original transaction

- app/services/invoice_rebilling_initialise.service.js
- test/services/invoice_rebilling_initialise.service.test.js
The WRLS team have spotted an issue with the rebilling process. When the `PATCH /rebill` endpoint is hit we generate the invoices and return their ID's. The process of copying the transactions and populating the new invoices happens in the background. As far as the client system is concerned the response is complete.
The issue that's been spotted is what happens if the client system was immediately to hit the `PATCH /generate` endpoint after rebilling an invoice? Currently, disaster! As long as at least one transaction has been created the generate process will kick off and create a summary for the bill run based on what is there at the time.
So, we need a solution. This change will update the rebill process to set the bill run's status as `pending`. Whilst the status is `pending` no …
> Fix - protect bill run when rebilling

- app/controllers/presroc/bill_runs_invoices.controller.js
- app/services/index.js
- app/services/invoice_rebilling.service.js
- app/services/invoice_rebilling_copy.service.js
- app/services/invoice_rebilling_initialise.service.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
- test/services/invoice_rebilling.service.test.js
- test/services/invoice_rebilling_copy.service.test.js
- test/services/invoice_rebilling_initialise.service.test.js
https://trello.com/c/A91YBKNC
As part of adding the fix to [protect bill run when rebilling](https://github.com/DEFRA/sroc-charging-module-api/pull/461) we've realised we need to do more work in the controller.
Specifically, we need to manage the status of the bill run, setting it to `pending` when the process starts and resetting it afterwards. We're already doing more than we would typically do in a controller handler for rebilling. So, it's time to do a spot of refactoring.
The first step involves updating `InvoiceRebillingService` to manage more of the process by moving the `InvoiceRebillingInitialiseService` into it. As part of that, we want to move what it currently does into its own service. `InvoiceRebillingService` can then become responsible for managing the process and in a …
> Refactor InvoiceRebillingService to do more

- .dockerignore
In [PR #467](https://github.com/DEFRA/sroc-charging-module-api/pull/467) the key change was to remove hpal-debug support. Our previous design for the `server.js` and it being the 'startup' file was directed by us trying to enable support for hpal-debug.
With it being dropped we also took the opportunity to update the project to more closely match the examples and documentation Hapi provides. We are going for the principle of least surprise for new devs to the team.
What we forgot to do was update our Docker ignore file to reflect the change in files, which then broke the Docker image if you tried to run it.
This fixes the issue.
> Fix broken Docker build

- app/models/invoice.model.js
- app/services/invoice_rebilling_copy.service.js
- app/services/invoice_rebilling_create_transaction.service.js
- db/migrations/20210706135346_alter_invoices.js
- test/services/invoice_rebilling_create_transaction.service.test.js
- test/services/invoice_rebilling_initialise.service.test.js
- test/support/helpers/invoice.helper.js
CMEA-64 https://eaflood.atlassian.net/browse/CMEA-64
During testing we encountered an issue we had not anticipated. If you attempt to rebill multiple invoices that happen to be for the same customer and financial year you get a DB conflict error.
```json
{
"statusCode": 409,
"error": "Conflict",
"message": "UniqueViolationError - Key (bill_run_id, customer_reference, financial_year, rebilled_type)= (5e969d83-8f32-483f-b90b-601bdece7d37, T1234567890A, 2020, C) already exists."
}
```
The problem is the constraint we use on the `invoices` table. This is actually at the core of the logic we use when transactions are added, to determine when a new invoice record needs creating or an existing one needs adding too. When adding transactions we always attempt to add a new invoice and rely on …
> Fix - Rebilling for same customer causes error

- app/presenters/index.js
- app/presenters/table_body.presenter.js
- test/presenters/table_body.presenter.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-1
Similar to how we generate transaction and customer files, we will be piping the contents of a db table row by row through a presenter which formats the row into sequentially-numbered columns, and then through a presenter which formats the row as CSV, and finally the row will be piped into a file.
We start developing this process by creating the table body presenter. Note that we may end up reusing this for the table head; if we do then we will rename the presenter accordingly.
> Create table body presenter

- app/presenters/index.js
- app/presenters/table_file.presenter.js
- app/services/index.js
- app/services/streams/stream_transform_using_presenter.service.js
- app/services/transform_table_to_file.service.js
- test/presenters/table_file.presenter.test.js
- test/services/streams/stream_transform_using_presenter.service.test.js
- test/services/transform_table_to_file.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-1
We want to take a database table and pipe its contents to a CSV file. We have [a presenter which will format the body of the table](https://github.com/DEFRA/sroc-charging-module-api/pull/476); the next stage is to create the service which will use this to transform a query into a CSV file.
This change introduces `TransformTableToFileService`, which adapts the existing `TransformRecordsToFileService`. We will later be looking at refactoring in order to share common functions; but for now we have this as an entirely separate service.
We make a small change to `StreamTransformUsingPresenterService` to allow us to reuse it here -- it does everything we need except it also adds in the index number needed …
> Create TransformTableToFile service

- app/services/export_table.service.js
- app/services/index.js
- test/services/export_table.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-1
We have `TransformTableToFileService` which can output a table to a file; we now need a service which accepts a table name and generates the required parameters (selecting query, column names, and output filename) which it then uses to call `TransformTableToFileService`.
A note on testing: it creates a customer change along with a customer file (so the customer change record can be populated with the file id) then exports the table and compares the customer change db record to the exported file. I would have preferred to completely mock the db calls to control exactly what data is fed to `TransformTableToFileService` but ran into difficulties with this. This therefore may be something to revisit in …
> Create table export service

- app/presenters/transaction_file_body.presenter.js
- test/presenters/transaction_file_body.presenter.test.js
https://eaflood.atlassian.net/browse/CMEA-12
The WRLS team on behalf of their users have told us that licence no. needs to be included in the transaction file we generate. This is so that the customer can work out how the minimum charge was calculated for each individual licence on an invoice.
Prior to this change, there was a requirement to not include licence no. if the transaction was subject to minimum charge or a compensation charge. This change updates the logic to ensures it's only blank when the transaction is a compensation charge.
> Include licence no. for min. charge in trans file

- app/plugins/invalid_characters.plugin.js
- test/features/invalid_characters.test.js
https://eaflood.atlassian.net/browse/CMEA-11
During initial business acceptance testing of the WRLS system and its integration with the CM API found a transaction file that was rejected by SOP.
This was tracked down to the line description containing 'inverted quotation marks'. It wasn't possible to get an exact example. But based on the description (and Google!) we have interpreted this as
- **“** [Left Double Quotation Mark](https://unicode-table.com/en/201C/) `U+201C`
- **”** [Right Double Quotation Mark](https://unicode-table.com/en/201D/) `U+201D`
This change adds these to our `InvalidCharactersPlugin` which will mean any `POST` request that contains them anywhere in its content will be rejected.
> Reject requests with inverted quotation marks

- test/models/invoice.model.test.js
Whilst working on another PR we spotted a couple of tests for the invoice model which are invalid/irrelevant. We think they are just the result of a copy and paste that never got cleaned up.
This change removes them.
> Remove invalid min. charge model tests

- test/controllers/presroc/bill_runs_invoices.controller.test.js
- test/services/validate_bill_run_licence.service.test.js
- test/support/helpers/new_bill_run.helper.js
- test/support/helpers/new_invoice.helper.js
- test/support/helpers/new_licence.helper.js
- test/support/helpers/new_transaction.helper.js
- test/support/test/helpers/new_bill_run.helper.test.js
- test/support/test/helpers/new_invoice.helper.test.js
- test/support/test/helpers/new_licence.helper.test.js
- test/support/test/helpers/new_transaction.helper.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-4
The new test helpers we have created will allow us to greatly streamline our tests. For example, if we want to test a transaction in isolation then we only need to create the transaction and everything else (bill run, invoice, licence, even authorised system and regime) will be handled for us.
However, if we do this then the bill run, invoice and licence will all be blank, which does not reflect the reality of what happens when we create things. We are therefore adding an `update` method to their helpers which will allow us to pass in an object of values to be added to the existing values. This is then used by the `add` method to cascade changes upwards, so if a transaction is created with certain …
> Test helpers cascade changes upwards

- test/support/helpers/new_bill_run.helper.js
- test/support/helpers/new_invoice.helper.js
- test/support/helpers/new_licence.helper.js
- test/support/test/helpers/new_invoice.helper.test.js
- test/support/test/helpers/new_licence.helper.test.js
- test/support/test/helpers/new_transaction.helper.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-4
While running through our new test helpers we noticed one small issue; although changes cascaded up to the next level (eg. from transaction to licence), they did not propagate any further than that. We quickly realised that although our `add` methods would call the `update` method of the parent, the `update` methods were not calling _their_ parents. This change resolves this.
> Test helpers pass all changes up

- app/routes/bill_run_licence.routes.js
https://trello.com/c/q3yaHhS7
The delete licence functionality has been checked and approved which means we are happy to make it available for use in `production`. This removes the routes filter that prevents the endpoint from being available in production.
> Enable delete licence in production

- app/services/send_customer_file.service.js
- app/services/send_file_to_s3.service.js
- app/services/send_transaction_file.service.js
- test/services/send_customer_file.service.test.js
- test/services/send_file_to_s3.service.test.js
- test/services/send_transaction_file.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-67
As part of creating the `DataExportService`, we need to be able to specify that we are creating a file whose key starts with `csv/`. During the creation of the original `SendFileToS3Service`, the customer and transaction files were all being given keys starting with `export/` so we built the service to automatically preface keys with this.
This change therefore changes `SendFileToS3Service` to no longer preface keys with `export/`, and updates the services using it (`SendCustomerFileService` and `SendTransactionFileService`) to add it instead. This will therefore enable `DataExportService` to add `csv/` as desired.
> Specify full key when sending to S3 bucket

- app/controllers/admin/test/test_data_export.controller.js
- app/controllers/index.js
- app/routes/test.routes.js
- app/services/data_export.service.js
- test/controllers/admin/test/test_data_export.controller.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-56
This change creates the `PATCH /admin/test/data-export` endpoint which can be used to manually trigger the data export process for testing purposes. The controller checks the response from `DataExportService` to see if it succeeds or fails and returns a `204` or `400` response accordingly.
> Create data export endpoint

- app/tasks/data_export.task.js
- app/tasks/index.js
- package.json
- test/tasks/data_export.task.test.js
https://eaflood.atlassian.net/browse/CMEA-68
For the customer changes export process we have a `task` which we call from a scheduled Jenkins job to kick off the process. This covers adding the same thing, only for the data export process that is currently [being developed](https://github.com/DEFRA/sroc-charging-module-api/pull/501).
> Add data export task

- app/services/data_export.service.js
- test/services/data_export.service.test.js
After seeing that [`DataExportTask`](https://github.com/DEFRA/sroc-charging-module-api/pull/505) logs its start and end, we realised it would probably be useful if `DataExportService` also did some logging. We have therefore added log messages when each table is successfully exported to a file, and when each file is successfully sent to S3.
> Add logging to `DataExportService`

- .env.example
- app/services/files/customers/send_customer_file.service.js
- app/services/files/transactions/send_transaction_file.service.js
- config/server.config.js
- test/services/files/customers/send_customer_file.service.test.js
- test/services/files/transactions/send_transaction_file.service.test.js
One of the [SonarCloud warnings we reviewed](https://github.com/DEFRA/sroc-charging-module-api/pull/516) related to the `REMOVE_TMP_FILES` environment variable (which controls whether customer and transaction files should be deleted after being sent to S3. We came to the conclusion that we don't actually need this environment variable -- it defaults to `true`, isn't currently set in any of our environments, and the chances of us ever needing to set it are exceedingly slim. We are therefore removing it.
> Delete `REMOVE_TMP_FILES` environment variable

- app/services/files/exports/export_data_files.service.js
- test/services/files/exports/export_data_files.service.test.js
We realised that `ExportDataFilesService` wasn't deleting its temp files after sending them to S3, which is inconsistent with how we handle temp files elsewhere (`SendCustomerFileService` and `SendTransactionFileService`). We therefore update `ExportDataFilesService` to do this.
> Delete files in `ExportDataFilesService`

- .github/workflows/ci.yml
We use [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) to
> [..] keep the packages you use updated to the latest versions.
Back in 2020 we also switched this project plus a number of other Defra ones to use [GitHub Actions](https://github.com/features/actions) instead of [Travis CI](https://www.travis-ci.com/). Travis brought in a [new pricing plan](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) that limited the build minutes to 1000 minutes per month which caused builds to start failing across all our projects.
This worked fine until Feb 2021 when GitHub made a change [to the permissions Dependabot PRs](https://github.blog/changelog/2021-02-19-github-actions-workflow …
> Fix dependabot builds

- package-lock.json
GitHub has highlighted issues with 3 packages the project depends on
- [path-parse](https://www.npmjs.com/package/path-parse)
- [normalize-url](https://www.npmjs.com/package/normalize-url)
- [hosted-git-info](https://www.npmjs.com/package/hosted-git-info)
Running `npm install` locally also highlights issues
```
77 packages are looking for funding
run `npm fund` for details
3 vulnerabilities (2 moderate, 1 high)
To address all issues, run:
npm audit fix
Run `npm audit` for details.
```
It suggests running `npm audit fix` and this change is the result of that.
> Use `npm audit fix to patch` vulnerabilities

- .github_changelog_generator
- CHANGELOG.md
We have always used the tool [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) to generate our `CHANGELOG.md`. It does this based on your PR history which is why we also try and ensure meaningful titles and descriptions are used.
We also use some non-default [labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) for our PR's and have always wondered how we could include them in the changelog. Anything with a custom label has always gone under the catch-all **Merged PR's** section.
Today we finally found the answer for [how to tell it to add sections](https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options) …
> Add custom sections to CHANGELOG

- README.md
The service has been live since June so is no longer a 'work in progress' 😄
This removes the message from the README.
> Remove WIP message from top of README

- .github/workflows/docker.yml
In [Add Docker build and push to GitHub workflows](https://github.com/DEFRA/sroc-charging-module-api/pull/522) we added a new workflow to automatically build Docker images after pushes to `main` and when new tags are added. We also settled on pushing to [GitHub Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) as our primary registry.
But we also highlighted that there is still some discussion about whether we should be using a single registry (and which one) plus our existing users are pulling things from [DockerHub](https://hub.docker.com/repository/docker/environmentagency/sroc-charging-module-api). So, to continue to support our clients and in case DockerHub wins out, this change amends the Docker …
> Add pushing to DockerHub to Docker workflow

- .github/dependabot.yml
Whilst working on [Add Docker build and push to GitHub workflows](https://github.com/DEFRA/sroc-charging-module-api/pull/522) we spotted in the README for [Docker Build-Push action](https://github.com/marketplace/actions/build-and-push-docker-images) a reference to the fact [Dependabot has native GitHub actions support](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem).
With 2 workflows using a number of actions, it makes sense to us to ensure we keep up to date with the versions we use in the same way we try and keep up to date with our npm dependencies.
So, this change updates the `dependabot.yml` workflow to include daily checks for our GitHub actions.
> Add GitHub actions to Dependabot checks

- app/README.md
https://eaflood.atlassian.net/browse/CMEA-103
Currently, the CHA only supports bill runs and transaction information for PRE-SROC charges. We are expecting in the coming months to start updating the service to handle [SROC](https://www.nfuonline.com/cross-sector/environment/water/irrigation-and-water-resources/ea-launches-consultation-on-strategic-review-of-abstraction-charges/) based charges.
The financial year a charge is applicable to determine the ruleset used. In the context of the CHA this means we'll be calling a different Rules Service endpoint and might mean we need to validate data differently or amend the behaviour of a service. We've done some initial work to prepare for this (See PRs #513, #514, and #519) and even done a [Sroc dev plan …
> Add dev guide amending code to handle new rulesets

- .github/workflows/docker.yml
In [Add pushing to DockerHub to Docker workflow](https://github.com/DEFRA/sroc-charging-module-api/pull/527) we updated our Docker workflow to include also pushing the images we are building to DockerHub as well as GitHub Container Registry (GHCR).
However, there is a flaw in our logic. We first generate the metadata used when building the images, including the docker tags, based on pushing to GHCR. We then use [sed](https://en.wikipedia.org/wiki/Sed) to update the tags to replace the GHCR address (`ghcr.io`) with DockerHub's (`docker.io`).
The flaw is we did not take into account the organisation. In GHCR we have permission to push packages to the [DEFRA organisation](https://github.com/DEFRA) but in DockerHub we are using [environmentagency](https://hub.docker.com/repository/docker/envir …
> Fix automatic push to DockerHub

- app/services/create_customer_details.service.js
- app/translators/customer.translator.js
- test/services/create_customer_details.service.test.js
- test/translators/customer.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-137
WRLS reported an issue with the customer details functionality. When submitting a customer record for a customer who already has a record, we should essentially overwrite the entire existing record with the new one. However what currently happens is that we only _update_ the existing record.
Say for example we have the following customer record:
```
{
"region": "A",
"customerReference": "AA11AAAA",
"customerName": "Customer Name",
"addressLine1": "House name",
"addressLine2": "Street name",
"addressLine3": "Town",
"addressLine4": "County",
"postcode": "PO57 0DE"
}
```
We want to change the details to remove the town and county. We submit the following customer change:
```
{
"region": "A", …
```
> Fix customer details `null` defect

- app/controllers/admin/customers.controller.js
- app/routes/customer.routes.js
- test/controllers/admin/customers.controller.test.js
When developing the QA customer files endpoints, we created a dummy endpoint `GET /admin/{regimeId}/customers` prior to creating `ListCustomerFilesService`. However during development, another endpoint `GET /admin/test/{regime}/customer-files` was created which we eventually used, but we did not remove the original incorrect endpoint. This change resolves this.
> Remove `GET /admin/{regimeId}/customers` endpoint

- .github/workflows/docker.yml
https://eaflood.atlassian.net/browse/CMEA-135
Though we are now building Docker images using a GitHub workflow, we inherited a process that is run on a Jenkins instance and pushes to a private [Artifactory](https://jfrog.com/artifactory/) instance. There is no sense in building an image in 2 places. Plus, if we build in just one place we know the image that's on [DockerHub](https://hub.docker.com/repository/docker/environmentagency/sroc-charging-module-api), in [GitHub Container Registry](https://github.com/DEFRA/sroc-charging-module-api/pkgs/container/sroc-charging-module-api), and in our Artifactory instance is one and the same.
Added to that we have been seeing more and more issues when the Jenkins instance builds. We're not sure of the reasons why but now when building we can expect …
> Generate and add unique tag in docker workflow

- .github/workflows/docker.yml
In [Generate and add unique tag in Docker workflow](https://github.com/DEFRA/sroc-charging-module-api/pull/543) we added a unique Docker tag for changes to `main`. In [Fix uppercase org name in unique docker tag](https://github.com/DEFRA/sroc-charging-module-api/commit/a074aada8b69cde7ab107a59cc0511ebd35c8226) we sorted an issue with the custom tag not being lowercase.
Unfortunately, the last fix had a typo 🤦. But we have also spotted the tag being generated is just the commit hash (`a074aad`). It should be like `v0.13.2-2-a074aad`.
This change fixes both issues.
> Fix 2 - issue with unique Docker Tag

- app/controllers/admin/authorised_systems.controller.js
- app/controllers/admin/regimes.controller.js
- app/controllers/admin/test/test_customer_files.controller.js
- app/controllers/admin/test/test_transactions.controller.js
- app/routes/authorised_system.routes.js
- app/routes/regime.routes.js
- app/routes/test.routes.js
- app/services/authorised_systems/view_authorised_system.service.js
- app/services/files/customers/view_customer_file.service.js
- app/services/index.js
- app/services/regimes/view_regime.service.js
- app/services/transactions/view_transaction.service.js
- test/controllers/admin/authorised_systems.controller.test.js
- test/controllers/admin/regimes.controller.test.js
- test/controllers/admin/test/test_customer_files.controller.test.js
- test/controllers/admin/test/test_transactions_controller.test.js
- test/services/authorised_systems/view_authorised_system.service.test.js
- test/services/files/customers/view_customer_file.service.test.js
- test/services/regimes/view_regime.service.test.js
- test/services/transactions/view_transaction.service.test.js
https://github.com/DEFRA/sroc-service-team/issues/68
When we first started building the project we focused on the admin endpoints, specifically `regimes` and `authorised_systems`. They were relatively simple and we needed the underlying data anyway in order to build the rest of the service.
But we were coming from a Ruby on Rails background which meant we used their conventions. Specifically, `show` for responding to a `GET` request.
In later endpoints, we switched to `view` as this was the terminology used by the rest of the team and in our documentation. So, we have an inconsistency in endpoint naming that this change resolves.
> Rename show endpoints to view

- app/controllers/customer_files.controller.js
- app/presenters/index.js
- app/presenters/list_customer_files.presenter.js
- app/services/files/customers/list_customer_files.service.js
- test/controllers/presroc/customer_files.controller.test.js
- test/presenters/list_customer_files.presenter.test.js
- test/services/files/customers/list_customer_files.service.test.js
- test/support/helpers/customer.helper.js
- test/support/helpers/general.helper.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907/backlog?selectedIssue=CMEA-166
We continue with this feature by implementing the `ListCustomerFilesService`, along with the `ListCustomerFilesPresenter` it uses to format its output. Note that we do not yet enforce the acceptance criteria that the output should default to 30 days; this will be handled in a future branch.
As part of development, we have amended `CustomerHelper.addCustomerFile()` to accept an export date, defaulting to the current date to avoid breaking existing tests. While doing this, we noticed that it was not setting the customer file status, so we fixed this.
Finally, we remove the service from `CustomerFilesController` -- after developing the service fully, the tests now fail as they don't perform …
> Implement `ListCustomerFilesService`

- app/controllers/customer_files.controller.js
- app/routes/customer_files.routes.js
- app/server.js
- test/controllers/presroc/customer_files.controller.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-57
We finish up by updating the route definition to accept an optional path parameter and add validation (which we also use to set the default of 30 days).
> List customer files controller and route

- app/routes/customer_files.routes.js
- test/controllers/presroc/customer_files.controller.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-57
While doing some final checks, we realised that the `positive()` validation requirement rejects the request if a parameter of `0` is used. We fix this by using `min(0)` instead.
> Amend 0 days parameter with `ListCustomerFilesController`

- app/presenters/list_customer_files.presenter.js
- app/services/files/customers/list_customer_files.service.js
- test/presenters/list_customer_files.presenter.test.js
https://eaflood.atlassian.net/browse/CMEA-57
In [Implement ListCustomerFilesService](https://github.com/DEFRA/sroc-charging-module-api/pull/554) we built the service which will be used by the new public version of our customer files endpoint.
The intent is now that we have a public version of the endpoint we should be able to delete `/admin/test` version. However, we've spotted that the 2 return very different data. The `/admin/test` one returns
```json
[
{
"id": "13273263-787c-4868-9fd4-1a6b8a25c415",
"regimeId": "48faa47b-e1fc-4892-ab8c-5d6862f1a99f",
"region": "A",
"fileReference": "nalac50001",
"status": "exported",
"exportedAt": "2021-09-21T22:40:45.398Z",
"createdAt": "2021-09-21T22:40:44.859Z",
"updatedAt": "2021-09-21T22:40:45.403Z"
}
]
```
The new public `/v2/{regime}/` one …
> Expand info returned in customer-files endpoint

- app/controllers/bill_runs_licences.controller.js
- app/services/licences/delete_licence.service.js
- test/controllers/presroc/bill_runs_licences.controller.test.js
- test/services/licences/delete_licence.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-141
Unlike other endpoints which set off a background task and return a response immediately, Delete Licence does not update the bill run status to reflect the fact that an operation is running which could affect the bill run values. We therefore update `DeleteLicenceService` to do this.
One case to consider is when deleting the licence causes the invoice to be empty and therefore deleted, which in turn causes the bill run to be empty, in which case the status will be changed to `initialised`. We ensure that this is not overwritten by reverting to the original status by checking whether the status changed during deletion before restoring it.
Finally, we update the service's unit tests to use our new …
> Delete Licence not updating bill run status

- app/services/files/customers/list_customer_files.service.js
- test/services/files/customers/list_customer_files.service.test.js
- test/support/helpers/general.helper.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-57
It was spotted during testing that any customer files exported at exactly midnight (ie. with a timestamp of `00:00:00.000` are not included in the service output. Although this is the edgiest of edge cases, it is still worth resolving, and it has a very simple cause and solution -- we were selecting the files to be included with `.where('exportedAt', '>', startDate)` when we should have been using `.where('exportedAt', '>=', startDate)`.
> Fix `ListCustomerFilesService` time boundary defect

- app/services/invoices/delete_invoice.service.js
- test/services/invoices/delete_invoice.service.test.js
https://eaflood.atlassian.net/browse/CMEA-171
After a discrepancy with a bill run's summary was reported we tracked it down to an error when a deminimis invoice is deleted.
Deminimis invoices (debits £5 or less) are not included in the bill run summary. This means when it's generated they are not included in the invoice count and total value. So, when deleted they should not impact those values in the bill run. The problem is that we are updating the bill run when a deminimis invoice is deleted.
This change fixes the issue and ensures the bill run summary is correctly updated when a deminimis invoice is deleted.
**How to reproduce**
Create a bill run and add 5 invoices; 4 standard and 1 deminimis. Generate the bill run and it will show 4 invoices in the summary. The invoice value will be …
> Fix deleting a deminimis invoice recalculation

- app/controllers/bill_runs_licences.controller.js
- test/controllers/bill_runs_licences.controller.test.js
While updating delete licence to set the status to `pending`, we inadvertently changed the call to `ValidateBillRunLicenceService` to pass the `billRun` object instead of `billRun.id`. We revert this here.
> Fix incorrect `ValidateBillRunLicenceService` parameter issue

- app/services/invoices/delete_invoice.service.js
- test/services/invoices/delete_invoice.service.test.js
https://eaflood.atlassian.net/browse/CMEA-171
Whilst testing [Fix deleting a deminimis invoice recalculation](https://github.com/DEFRA/sroc-charging-module-api/pull/561) we also ensured we checked what happens when deleting other invoice types. Immediately zero value invoices fell out as having an issue. Because they are zero value the bill run `invoice_value` remains unaffected. But we still decrement the invoice count, just like we were doing for deminimis invoices, even though zero value invoices are also not included in the invoice count.
This change fixes the `DeleteInvoiceService` to also ignore zero value invoices when it comes to updating a bill run's summary details.
> Fix deleting a zero value invoice recalculation

- test/controllers/admin/test/test_bill_runs.controller.test.js
- test/support/generators/bill_run.generator.js
https://eaflood.atlassian.net/browse/CMEA-141
We've been trying to create a test where we can see the bill run status go to `pending` when a licence is deleted. Problem is, with a whole bunch of transactions the service is proving too fast to see it in our acceptance tests.
We have the bill run generator test endpoint. The only issue is the current counts relate to the number of invoices. The number of transactions per invoice is set in the code.
To give us a bit more flexibility, this change allows us to affect the number of transactions added per invoice by the generator.
It also adds a new invoice type of `standard` which just adds debit transactions.
```json
{
"region": "A",
"transactionMultiplier": 5,
"mix": [
{ "type": "mixed-invoice", "count": 1 },
{ "type": "mixed-credit", …
```
> Update test bill run generator with trans. multiplier

- .env.example
- .labrc.js
- app/server.js
- app/services/charges/request_rules_service_charge.service.js
- config/rules_service.config.js
- docker-compose.yml
- package-lock.json
- package.json
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-167
We [previously fixed proxy support](https://github.com/DEFRA/sroc-charging-module-api/pull/511) for requests going to the Rules Service, however this is also needed for S3 requests -- WRLS are currently having issues with sending bill runs in their local setup and this may be due to S3 requests failing for proxy reasons.
While investigating how to configure the AWS SDK to use a proxy, we discovered that the [`tunnel`](https://www.npmjs.com/package/tunnel) package we are using for Rules Service proxying does not appear to be currently maintained. Researching a suitable alternative led us to [`global-agent`](https://www.npmjs.com/package/global-agent), which would allow us to configure the proxy in …
> Replace existing proxy config with `global-agent`

- app/presenters/customer_file_body.presenter.js
- app/translators/customer.translator.js
- test/presenters/customer_file_body.presenter.test.js
- test/services/create_customer_details.service.test.js
- test/translators/customer.translator.test.js
https://eaflood.atlassian.net/browse/CMEA-181
Currently, `postcode` is required in any customer change requests to the API. We think this decision was rooted in the fact it's a required field in the customer file that goes to SSL with the customer changes in it.
But the original A/C on the story for developing it for CM v2 was
> AC6. Where the postcode is missing from the incoming request, detail field 11 in the customer file is populated with a "." (full stop).
Having double-checked the code in CM v1 we can see this is in the request validation
```javascript
postcode: stringValidator.max(60).allow('', null)
```
When it comes to the customer file the CM is expected to replace blank postcodes with `.`. Again, we can see this is CM v1
```javascript
handlePostcodeValue (value) {
if (value && …
```
> Fix postcode should not be a required property

- app/services/licences/delete_licence.service.js
https://eaflood.atlassian.net/browse/CMEA-141
In [Delete Licence not updating bill run status](https://github.com/DEFRA/sroc-charging-module-api/pull/559) we thought we solved a problem whereby not setting the bill run status to something other than `generated` when deleting a licence client services couldn't tell when the operation was complete.
The fact we couldn't _see_ the bill run get set to `pending` during testing we just chalked up to the speed of the delete.
On review though, we realised there is a problem with the fix. It is updating the status within the same DB transaction as the delete of the licence. This means as far as the client is concerned, it never sees the status change.
This fixes the previous fix by removing the DB transaction element.
<details>
<summary>Evidence …
> Fix pending status in delete licence

- app/services/licences/delete_licence.service.js
- test/services/licences/delete_licence.service.test.js
- test/support/helpers/new_invoice.helper.js
- test/support/helpers/new_licence.helper.js
- test/support/helpers/new_transaction.helper.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-178
When deleting a licence, the bill run summary is not correctly updated in scenarios where the invoice changes "type". For example, from a debit/credit to zero value; from a credit to a debit; etc. In these cases, the bill run level values `creditNoteCount`, `creditNoteValue`, `invoiceCount` and `invoiceValue` were not correctly being adjusted to account for the change in type.
This was initially discovered in the following scenario:
* A debit transaction is created on licence `L001`;
* A zero-value transaction is created on licence `L002`;
* Licence `L001` is deleted;
* The invoice count should be `0` but it remains `1`.
(Note that the original defect report noted that `creditNoteValue` is also …
> Fix Delete Licence not correctly updating bill run summary

- app/controllers/calculate_charge.controller.js
- app/routes/calculate_charge.routes.js
- app/services/charges/validate_charge.service.js
- app/services/index.js
- test/controllers/calculate_charge.controller.test.js
- test/services/charges/validate_charge.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-194
In order to test the SRoC validation, we create a `ValidateChargeService` which passes the provided payload through the translator to validate it, then returns the translated data in the response. We create a `calculate` endpoint for this (renaming the existing endpoint to `calculateV2` as per our convention) and connect this to a `/v3/{regimeSlug}/calculate-charge` route.
Note that this will solely be used to test the validation, and will be removed once we move on to actually sending charge requests to the Rules Service.
> Create `ValidateChargeService` and v3 route

- app/services/transactions/create_transaction.service.js
- app/translators/index.js
- app/translators/transaction_presroc.translator.js
- app/translators/transaction_sroc.translator.js
- test/support/helpers/new_transaction.helper.js
- test/support/helpers/transaction.helper.js
- test/translators/transaction_presroc.translator.test.js
- test/translators/transaction_sroc.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-203
We implement the sroc-specific validation rules described in the card. Note that this PR fails SonarCloud due to code duplication between the presroc and sroc transaction validators; we won't be in a suitable place to fully refactor these until we've established the db fields to use, which will be done as part of the "create transaction" PR to follow.
> Create transaction validation for sroc

- app/controllers/admin/test/test_bill_runs.controller.js
- app/controllers/bill_runs_transactions.controller.js
- app/services/transactions/create_transaction.service.js
- app/translators/transaction_presroc.translator.js
- test/services/transactions/create_transaction.service.test.js
- test/support/fixtures/create_transaction/presroc/simple.json
- test/support/helpers/bill_run.helper.js
- test/support/helpers/new_bill_run.helper.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-202
Ahead of our v3 route, we update `CreateTransactionService` to read `ruleset` from the bill run that the transaction is being created on. At present, we only support `presroc` bill runs; `sroc` will be added in a future PR.
Since the v2 route optionally accepts `ruleset` in the payload, we update the presroc validation to only allow `presroc`, and to default to `presroc` when not given. This means that the output of the translator contains the ruleset which is needed by `CalculateChargeService` when we pass the validated data on to it.
Note that all of this required a change to our test helpers; every test which uses a bill run helper to create a bill run followed by `CreateTransactionService` …
> Update `CreateTransactionService` to accept `ruleset`

- app/presenters/calculate_charge_sroc.presenter.js
- app/presenters/rules_service_sroc.presenter.js
- app/translators/rules_service_presroc.translator.js
- app/translators/rules_service_sroc.translator.js
- test/translators/rules_service_sroc.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-202
While working on Create Transaction, we realised that the various translators and presenters used in the create transaction flow aren't quite aligned in terms of their input and outputs. This PR seeks to align them by ensuring that leftover placeholder translation/presentation is replaced with the actual db fields to be used.
We found that none of the `_translations()` in `RulesServiceSrocTranslator` were needed, as all the data items returned by the translator are set in `constructor()`. We therefore remove them so that `_translations()` returns an empty object. Following this, we checked `RulesServicePresrocTranslator` and spotted the `chargeValue` was similarly unneeded, as we set it in …
> Align sroc translator and presenter fields

- app/translators/rules_service_sroc.translator.js
- test/translators/rules_service_sroc.translator.test.js
We observed during testing that the Rules Service only returns a value for `compensationChargePercentage` if the charge request was for a compensation charge. If it wasn't a compensation charge, `compensationChargePercentage` is not included in the response, causing problems as we have set this as a required field.
We fix this by changing it from being a required field to one that defaults to `null`, and updating the translator to leave the percentage value as `null` in this situation instead of trying to convert it to a number.
> Handle undefined `compensationChargePercentage` in Rules Service response

- app/translators/rules_service_sroc.translator.js
- test/translators/rules_service_sroc.translator.test.js
[Our previous fix](https://github.com/DEFRA/sroc-charging-module-api/pull/617) for the SRoC Rules Service response unfortunately failed in test -- we had misunderstood the cause of the problem, which wasn't that `compensationChargePercentage` was missing from the Rules Service response, but rather it was present but had a value of `null`. This PR fixes this.
> Handle null `compensationChargePercentage` in Rules Service response

- app/lib/static_lookup.lib.js
- app/models/bill_run.model.js
- app/models/invoice.model.js
- app/services/bill_runs/generate_bill_run.service.js
- app/services/licences/delete_licence.service.js
- test/models/bill_run.model.test.js
- test/models/invoice.model.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-211
SRoC invoices will have a different deminimis limit to pre-SRoC invoices. We therefore need to be able to support a different deminimis limit where required.
We initially wanted to update the `deminimis` modifier on `InvoiceModel` to take the ruleset from the parent bill run and apply the appropriate value. However this proved difficult to implement, due to the way Objection translated the query to SQL; we ran into problems when trying to apply a patch to the selected invoices.
We therefore took a fresh look at how we were using this modifier. After checking the code we saw that we only used it once, in `GenerateBillRunService`. And since we had the bill run there, we realised it made more sense to …
> Update deminimis to support SRoC

- app/plugins/invalid_characters.plugin.js
- test/features/invalid_characters.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-203
We overlooked the caret/circumflex character `^` when building the list of invalid characters to be rejected by `InvalidCharactersPlugin`. We therefore add it to the list.
> Add caret/circumflex to `InvalidCharactersPlugin`

- app/presenters/view_bill_run.presenter.js
- app/presenters/view_bill_run_invoice.presenter.js
- app/routes/bill_run.routes.js
- app/services/bill_runs/view_bill_run.service.js
- test/controllers/bill_runs.controller.test.js
- test/presenters/view_bill_run.presenter.test.js
- test/services/bill_runs/view_bill_run.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-215
The key difference between presroc and sroc for View Bill Run is that `minimumChargeInvoice` is only included in the output when viewing a presroc bill run. We do this by updating `ViewBillRunService` to pass `ruleset` to `ViewBillRunPresenter`. In turn, this passes it to `ViewBillRunInvoicePresenter` (note that presenters can only accept a single `data` parameter so we need to add this to the data object we pass in). Finally, the invoice presenter only includes `minimumChargeInvoice` in the output if the ruleset is `presroc`.
Once this is done, we add a v3 route and unit test. Note that we do not see the changes made here to be a breaking change, so the v2 and v3 routes both use the same …
> View SRoC Bill Run and v3 route

- app/services/bill_runs/generate_bill_run.service.js
- test/services/bill_runs/generate_bill_run.service.test.js
We discovered a defect during development, where the `deminimisInvoice` and `zeroValueInvoice` flags would not always be correct if the invoice had changed state after the bill run was generated. For example:
- A bill run is created and has a deminimis transaction added to it
- The bill run is generated; the `deminimisInvoice` flag for the invoice is correctly set to `true`, and the invoice is not included in the bill run summary stats
- An additional transaction is added to the invoice, taking the invoice value over the deminimis limit
- The bill run is generated again; the `deminimisInvoice` flag is still `true` when it should have changed to `false`, and the invoice is still not included in the bill run summary stats
This was caused by the way we set the `deminimisInvoice` flag during …
> Fix invoice flags not correctly reflecting state change

- app/presenters/view_invoice.presenter.js
- app/presenters/view_licence.presenter.js
- app/presenters/view_transaction.presenter.js
- app/routes/bill_run_invoice.routes.js
- app/services/invoices/view_invoice.service.js
- test/controllers/bill_runs_invoices.controller.test.js
- test/presenters/view_invoice.presenter.test.js
- test/presenters/view_transaction.presenter.test.js
- test/services/invoices/view_invoice.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-216
We create a `GET /v3/{regimeSlug}/bill-runs/{billRunId}/invoices/{invoiceId}` route and point it to the same `ViewInvoiceService` as the v2 route. We don't touch the v2 route as the changes implemented here are not considered to be breaking changes, so we can leave v2 as-is. Then we update the service and its associated presenters to handle SRoC invoices:
- `ruleset` is added to the invoice-level view
- the invoice-level `minimumChargeInvoice` flag is hidden for SRoC invoices
- the transaction-level `subjectToMinimumCharge` & `minimumChargeAdjustment` flags are also hidden when viewing an SRoC invoice
Applying the deminimis limit (as referred to in the ACs) is handled when the bill run summary is …
> View SRoC Invoice and v3 route

- docs/versioning.md
Recent work updating the CM to support SRoC alongside pre-SRoC has meant that an endpoint can now accept different sets of request parameters depending on which ruleset the request is for. Getting the Swagger syntax right for describing the request formats and providing examples was a little fiddly to implement (not helped by the fact the VS Code extension we use doesn't support previewing multiple sets of examples!) so we document it here for future reference.
> Add Swagger request versioning to docs

- app/models/bill_run.model.js
- app/services/bill_runs/send_bill_run_reference.service.js
- app/services/files/transactions/send_transaction_file.service.js
- test/services/bill_runs/send_bill_run_reference.service.test.js
- test/services/files/transactions/send_transaction_file.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-225
As part of our drive to standardise bill run statuses, we amend the send bill run process as follows:
- At the start of the process, the bill run status is set to `pending` to show that the details are being updated and therefore subject to change;
- Once this is done, the status is set to `sending` and the process continues to the transaction file creation stage.
- After the file is created, the status is set to either `billed` or `billing_not_required` (as is currently the case).
> Amend send bill run statuses

- app/models/bill_run.model.js
- app/services/bill_runs/delete_bill_run.service.js
- app/services/bill_runs/generate_bill_run.service.js
- app/services/bill_runs/generate_bill_run_validation.service.js
- test/models/bill_run.model.test.js
- test/services/bill_runs/delete_bill_run.service.test.js
- test/services/bill_runs/generate_bill_run.service.test.js
- test/services/bill_runs/generate_bill_run_validation.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-226
We are moving to using `pending` as our standard status meaning "bill run is being updated, check back later". This change replaces the specific statuses `generating` and `deleting` with our general status `pending`.
> CMEA-226 Make use of pending status consistent

- app/routes/bill_run_invoice.routes.js
- test/controllers/bill_runs_invoices.controller.test.js
https://eaflood.atlassian.net/browse/CMEA-232
Since there is no change in behaviour between v2 and v3 we simply create a v3 route `/v3/{regimeSlug}/bill-runs/{billRunId}/invoices/{invoiceId}` and point it to the existing controller.
N.B. We are creating a series of `/v3` routes even where no change is required to give a clear distinction between a workflow that supports both SROC and PRESROC (v3) and one that only supports PRESROC (v2).
> CMEA-232 Add new V3 delete invoice endpoint

- app/translators/calculate_charge_sroc.translator.js
- test/translators/calculate_charge_sroc.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-240
We have agreed with WRLS that we will remove one of our validation checks on an incoming charge -- we will no longer be validating that `section127Agreement` is `false` if `compensationCharge` is `true`. We therefore remove this validation rule. (This PR labelled as `bug` as it was a "bug" in our requirements)
> Remove unneeded validation

- app/translators/calculate_charge_base.translator.js
- app/translators/calculate_charge_presroc.translator.js
- app/translators/calculate_charge_sroc.translator.js
- app/translators/transaction_base.translator.js
- app/translators/transaction_presroc.translator.js
- app/translators/transaction_sroc.translator.js
- test/translators/calculate_charge_presroc.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-214
When we were implementing sroc charge validation, we realised that we could validate some fields in a better way than we were validating them for presroc. This change therefore updates the transaction translators so that this improved validation is also applied to the presroc ruleset, by moving the validation to the base class:
- We validate that if `twoPartTariff` is `true` then `section127Agreement` is also `true`
- We validate that `twoPartTariff` and `compensationCharge` are not both set to `true`
- We validate that the max length of `chargePeriod` is 150 chars. Note that this change is made to the transaction translator, rather than the charge translator.
For sroc fields where text has to be …
> Add additional presroc validation

- app/translators/calculate_charge_presroc.translator.js
- test/translators/calculate_charge_presroc.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907
After merging the previous validation work, we realised we had used an outdated spreadsheet to compile the lists of strings to be validated against. We fix this here.
> Amend presroc validation lists

- app/routes/bill_run.routes.js
- test/controllers/bill_runs.controller.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-229
Since we are not changing the behaviour of the view bill run status endpoint, we simply create a new route `/v3/{regimeSlug}/bill-runs/{billRunId}/status` and point it to the existing controller.
> Create v3 view bill run status route

- app/routes/bill_run.routes.js
- test/controllers/bill_runs.controller.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-237
Since we are not changing the behaviour of the approve bill run endpoint, we simply create a new route `PATCH /v3/{regimeSlug}/bill-runs/{billRunId}/approve` and point it to the existing controller.
> Create v3 approve bill run route

- app/translators/calculate_charge_base.translator.js
- app/translators/calculate_charge_presroc.translator.js
- app/translators/calculate_charge_sroc.translator.js
- test/translators/calculate_charge_presroc.translator.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-214
Previously, presroc and sroc had a different list of valid values for `regionalChargingArea`. However we have had confirmation that these lists can be the same; therefore, we delete the lists from the individual translators, and put the single list we want to use on the base translator, so they both validate against the same list.
We also move the validation rule to the base validator, as we have agreed that the behaviour should be the same for both. This means a slight change in how the field is validated for presroc to bring it in line with sroc: previously, the field was always required for presroc, whereas now it is only required if `compensationCharge` is `true`. In practice, …
> Align presroc and sroc `regionalChargingArea` validation

- app/translators/calculate_charge_presroc.translator.js
- test/translators/calculate_charge_presroc.translator.test.js
We previously refactored our presroc and sroc charge validation so that any validation we want to apply to both rulesets is placed in a shared base translator. We did this with our sroc validation which ensures that both `twoPartTariff` and `compensationCharge` aren't both true, as we wanted this to also apply to presroc. However, we overlooked removing the existing `twoPartTariff` validation from the presroc translator, which meant that the specific conditional validation was then being overwritten with the basic "ensure this field is present" validation we had for presroc. We therefore remove this from the presroc translator to ensure that the conditional validation applies to both rulesets.
> Remove `twoPartTariff` validation from presroc translator

- app/services/bill_runs/send_bill_run_reference.service.js
- app/services/next_references/next_transaction_reference.service.js
- db/migrations/20220112115027_alter_sequence_counters.js
- test/services/next_references/next_transaction_reference.service.test.js
https://eaflood.atlassian.net/browse/CMEA-220
A transaction reference is assigned to each invoice to be billed when a bill run is `sent`. There is a need for the SROC references to be distinguishable from PRE-SROC. In the [TCM](https://github.com/DEFRA/sroc-tcm-admin) this is done by adding a `T` to the end of the reference.
We've been asked to do the same in the CM. We also need to maintain separate sequences.
So, this change handles updating the sequence counters to allow for a new SROC transaction number sequence.
> CMEA-220 Add SROC transaction number sequence

- app/routes/bill_run.routes.js
- test/controllers/bill_runs.controller.test.js
https://eaflood.atlassian.net/browse/CMEA-239
Since we are not changing the behaviour of the send bill run endpoint, we simply create a new route `PATCH /v3/{regimeSlug}/bill-runs/{billRunId}/send` and point it to the existing controller.
> Create v3 send bill run route

- app/services/bill_runs/send_bill_run_reference.service.js
- app/services/files/customers/prepare_customer_file.service.js
- app/services/next_references/base_next_file_reference.service.js
- app/services/next_references/next_customer_file_reference.service.js
- app/services/next_references/next_transaction_file_reference.service.js
- config/rules_service.config.js
- test/services/bill_runs/send_bill_run_reference.service.test.js
- test/services/next_references/base_next_file_reference.service.test.js
- test/services/next_references/next_transaction_file_reference.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-221
Currently, presroc transaction files have a filename in the format `nalri50001`. We want sroc transaction files to have a filename in the format `nalri50001t`, ie. with a `t` suffix. However, we want the sroc and presroc sequences to be continuous, ie. `nalri50001t` would be followed by either `nalri50002` or `nalri50002t`, which would be followed by either `nalri50003` or `nalri50003t`, etc.
We implement this as follows:
- We update `BaseNextFileReferenceService` to no longer have a generic filename template in `_response()`, but instead expect services that extend it to provide their own `_response()` method;
- We add a `_response()` method to `NextTransactionFileReferenceService` which checks …
> Create SRoC transaction file references

- app/routes/bill_run.routes.js
- test/controllers/bill_runs.controller.test.js
https://eaflood.atlassian.net/browse/CMEA-233
Since we are not changing the behaviour of the delete bill run endpoint, we simply create a new route `DELETE /v3/{regimeSlug}/bill-runs/{billRunId}` and point it to the existing controller.
> Create v3 Delete Bill run route

- app/routes/customer_details.routes.js
- test/controllers/customer_details.controller.test.js
https://eaflood.atlassian.net/browse/CMEA-262
Since we are not changing the behaviour of the v3 customer changes endpoint, we simply create a new route `POST /v3/{regimeSlug}/customer-changes` and point it to the existing controller.
> Create v3 Post customer changes route

- app/routes/customer_files.routes.js
- test/controllers/customer_files.controller.test.js
https://eaflood.atlassian.net/browse/CMEA-263
Since we are not changing the behaviour of the v3 customer files endpoint, we simply create a new route `GET /v3/{regimeSlug}/customer-files/{days}` and point it to the existing controller.
> Create v3 Get customer files route

- app/translators/calculate_charge_base.translator.js
- app/translators/calculate_charge_presroc.translator.js
- app/translators/calculate_charge_sroc.translator.js
- test/translators/calculate_charge_presroc.translator.test.js
We previously changed the charge validation for the field `regionalChargingArea` as part of our work to bring presroc validation in line with sroc, by making the field optional if `compensationCharge` is set to `false`. This was done on the basis that this isn't part of the charge calculation for either ruleset, and therefore doesn't need to be sent to the Rules Service.
However, it turns out that the Rules Service still requires `regionalChargingArea` in order to calculate the `sucFactor` of a presroc charge, and therefore presroc requests will fail if this field isn't present. Note that `sucFactor` is not part of sroc, so is still optional for that ruleset.
We therefore revert our previous change and make `regionalChargingArea` a required field for presroc, regardless of …
> Revert presroc `regionalChargingArea` validation change

- app/services/invoices/invoice_rebilling_validation.service.js
- test/services/invoices/invoice_rebilling_validation.service.test.js
When an invoice is rebilled onto a new bill run, we should have been validating that the new bill run's status is an "editable" status (ie. `initialised` or `generated`). We therefore update `InvoiceRebillingValidationService` to check this.
> Validate new bill run status when rebilling

- app/lib/static_lookup.lib.js
- test/models/bill_run.model.test.js
- test/services/licences/delete_licence.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-256
We disable deminimis for sroc by setting the deminimis limit to `0`. We also update unit tests to demonstrate that even the smallest invoice is not identified as deminimis for sroc.
> Remove sroc deminimis limit

- app/presenters/index.js
- app/presenters/transaction_file_presroc_body.presenter.js
- app/presenters/transaction_file_sroc_body.presenter.js
- app/services/files/transactions/generate_presroc_transaction_file.service.js
- test/presenters/transaction_file_presroc_body.presenter.test.js
- test/presenters/transaction_file_sroc_body.presenter.test.js
We rename the existing `TransactionFileBodyPresenter` to `TransactionFileSrocBodyPresenter`, and proceed to create `TransactionFileSrocBodyPresenter` which formats the data for an sroc transaction file. Some additional refactoring could be done to consolidate common functions between the sroc and presroc body presenters but we will do this later once we've completed the sroc transaction file work.
Note that we don't actually use this presenter yet when generating an sroc transaction file; we'll be adding this functionality in a future PR.
> Develop sroc transaction file body presenter

- app/presenters/transaction_file_head.presenter.js
- test/presenters/transaction_file_head.presenter.test.js
- test/services/files/transactions/generate_presroc_transaction_file.service.test.js
As per AC1 in the card, the format of the transaction file head is pretty much the same for both presroc and sroc. However the way it turns a file reference into a file number needs to be changed.
The existing code takes a reference in the format `nalwi50003` and extracts the last 5 characters, ie. `50003`. However for sroc references like `nalwi50003t` we want to extract the last 6 characters and make it upper case, ie. `50003T`.
Since file references always have 5 letters at the start, we simply change this to extract the 6th character onwards and upper-case it.
> Amend transaction file head presenter for sroc

- app/translators/calculate_charge_base.translator.js
- app/translators/calculate_charge_presroc.translator.js
- app/translators/calculate_charge_sroc.translator.js
- app/translators/transaction_sroc.translator.js
- test/translators/calculate_charge_sroc.translator.test.js
We need to put the prorata days string in the sroc transaction file (as we do with presroc transaction files), however we overlooked this when setting up our sroc charge. Therefore we need to update `CalculateChargeSrocTranslator` so that it adds this in. We do this by refactoring the prorata days methods into the `CalculateChargeBaseTranslator`.
> Add `prorataDays`/`lineAttr3` to sroc charge

- app/presenters/transaction_file_sroc_body.presenter.js
- app/services/files/transactions/base_generate_transaction_file.service.js
- app/services/files/transactions/generate_presroc_transaction_file.service.js
- app/services/files/transactions/generate_sroc_transaction_file.service.js
- app/services/files/transactions/send_transaction_file.service.js
- app/services/index.js
- test/presenters/transaction_file_sroc_body.presenter.test.js
- test/services/files/transactions/base_generate_transaction_file.service.test.js
- test/services/files/transactions/generate_sroc_transaction_file.service.test.js
- test/services/files/transactions/send_transaction_file.service.test.js
We create `GenerateSrocTransactionFileService` which uses `TransactionFileSrocBodyPresenter` (along with the regular head and tail presenters) to format a transaction file for sroc.
Testing this uncovered a small defect with `TransactionFileSrocBodyPresenter` -- we check whether `headerAttr2` and `regimeValue19` equal `1`, but these are stored as strings in the db so we fix this to check against `'1'` instead.
> Generate sroc transaction file service

- app/translators/calculate_charge_sroc.translator.js
- app/translators/transaction_sroc.translator.js
- test/support/fixtures/calculate_charge/sroc/simple_request.json
- test/support/fixtures/create_transaction/sroc/simple.json
- test/translators/calculate_charge_sroc.translator.test.js
https://eaflood.atlassian.net/browse/CMEA-258
We update `CalculateChargeSrocTranslator` to validate `adjustmentFactor` and translate it to `regimeValue19`. We also update `TransactionSrocTranslator` to accept it and pass it on to the charge translator.
> Add `adjustmentFactor` to sroc validation

- app/presenters/rules_service_sroc.presenter.js
https://eaflood.atlassian.net/browse/CMEA-258
Now that we expect and validate `adjustmentFactor` for sroc charge and transaction requests, the next thing we need to do is include this in Rules Service requests for sroc, which is simply a case of adding it to `RulesServiceSrocPresenter`.
> Add `adjustmentFactor` to `RulesServiceSrocPresenter`

- app/presenters/transaction_file_sroc_body.presenter.js
- app/services/files/transactions/generate_sroc_transaction_file.service.js
- test/presenters/transaction_file_sroc_body.presenter.test.js
- test/services/files/transactions/generate_sroc_transaction_file.service.test.js
https://eaflood.atlassian.net/browse/CMEA-258
If `adjustmentFactor` is anything other than `1` then we want to add `Other` to the list of reductions in the sroc transaction file. We do this by amending `GenerateSrocTransactionFileService` to retrieve `regimeValue19` as part of the select query to get all the required data for the transaction file, then updating `TransactionFileSrocBodyPresenter` to add `Other` to the list of reductions based on its value.
> Use `adjustmentFactor` in sroc transaction file

- app/services/files/transactions/base_generate_transaction_file.service.js
- test/services/files/transactions/generate_presroc_transaction_file.service.test.js
We found during testing that transaction files were not being sorted in the correct order (first by transaction reference, then by licence number, and then by compensation charge). On investigation we traced this back to the work we did to refactor transaction generation into `BaseGenerateTransactionFileService`.
The issue turned out to be a simple one! Methods like `.select()` expect multiple parameters, eg:
```js
.select('first_field', 'second_field', 'third_field')
```
When we moved the fields into a function, we had that function return an array and then use the spread operator to turn that array into the required series of parameters:
```js
.select(...this._select())
```
This is fine! But what isn't fine is that we did the same for …
> Fix transaction file sort order

- app/services/bill_runs/validate_bill_run_region.service.js
- app/services/invoices/invoice_rebilling_validation.service.js
- test/services/bill_runs/validate_bill_run_region.service.test.js
- test/services/invoices/invoice_rebilling_validation.service.test.js
https://eaflood.atlassian.net/browse/CMEA-155
We update the wording of some of our error messages so we are more consistent about referring to entities being "linked to" other entities (ie. a bill run is now "linked to" a region, rather than being "for" that region).
> Give consistent "not linked" error responses

- app/controllers/bill_runs_invoices.controller.js
Whilst regression testing v0.18.0 we came across this error
```
TypeError: Cannot read properties of undefined (reading 'creditLineCount')
at Function._billRunPatch (/home/node/app/app/services/invoices/delete_invoice.service.js:82:61)
at Function._deleteInvoice (/home/node/app/app/services/invoices/delete_invoice.service.js:46:31)
at /home/node/app/app/services/invoices/delete_invoice.service.js:36:22
at /home/node/node_modules/knex/lib/transaction.js:183:22
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'id')
at Function.go (/home/node/app/app/services/invoices/delete_invoice.service.js:41:61)
at runMicrotasks (<anonymous>)
at processTicksAndRejections …
```
> Fix creditLineCount undefined in delete invoice

- app/presenters/transaction_file_sroc_body.presenter.js
- test/presenters/transaction_file_sroc_body.presenter.test.js
- test/services/files/transactions/generate_sroc_transaction_file.service.test.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-309
The following changes have been requested for the sroc transaction file:
* Line attribute 1 (col 26) should be populated for all transactions -- a change from the current behaviour of populated for all except compensation charge transactions
* Line attribute 7 (col 32) and line attribute 11 (col 36) should all have `pence` appended without a space between eg. `969000pence`
* Line attribute 9 (col 34) should be in the format `${supportedSourceValue}pence (${supportedSourceName})` eg. `1881600pence (Kielder)`.
* Line attribute 10 (col 35) should be in the format `Calculated using reported abstracted quantity (${actualVolume}ML) and the charge reference, which is based on the authorised quantity`
> Change SRoC transaction file after user feedback

- Dockerfile
We've just got the GitHub action `.github/workflows/docker.yml` working again but it has highlighted a new issue. The version of Node the CHA is using is now a few versions behind. This means the latest versions of NPM are no longer compatible with it.
This change fixes the issue specifying the version of NPM to install.
> See https://nodejs.org/en/about/previous-releases for Node and NPM compatibility
> Fix incompatible npm version in Dockerfile

- .github/workflows/docker.yml
In [Remove pushing to Docker Hub](https://github.com/DEFRA/sroc-charging-module-api/pull/1059) we wanted to remove the step that logged us into Docker Hub as we no longer have access to that as an image repo. We thought removing the login step was all that was needed but we overlooked that we were still generating a label that [docker/build-push-action@v5](https://github.com/docker/build-push-action/tree/v5/) uses to try and attempt to push the image to.
Removing that should fix the issue.
But then we reflected on what other changes we've done in the [sroc-tcm-admin](https://github.com/DEFRA/sroc-tcm-admin) repo recently in its Docker workflow.
To get it ready for using AWS ECS and ECR we had to take a deeper dive into [metadata-action](https://github.com/docker/metadata-action) and how …
> Fix and update Docker GitHub workflow

- .github/workflows/docker.yml
We're the last service using the Defra Artifactory and our web-ops friends would like to retire it. [AWS ECR](https://aws.amazon.com/ecr/) is now the norm for services and they would like it if we could migrate to using it instead.
The first step to that is confirming we can push our image to the registry they have configured.
This change updates our `docker.yml` GitHub action to push to ECR instead of GHCR, which hasn't been working for more than 2 months now.
> Push docker image to AWS ECR

- docker-compose.yml
When rebuilding the project on a new machine, we saw the following warning in the Docker build output.
```text
WARN[0000] /Users/acruikshanks/projects/defra/sroc-charging-module-api/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
Since we built this project, the [version property has been made obsolete](https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete). Docker now always attempts to interpret your compose file against the latest schema, so you can automatically benefit from the latest features and improvements.
So, we can safely delete the property and remove the warning from our output.
> See also [Do you still use version in Docker …
> Remove version property from Docker compose

- app/presenters/transaction_file_sroc_body.presenter.js
- test/presenters/transaction_file_sroc_body.presenter.test.js
- test/services/files/transactions/generate_sroc_transaction_file.service.test.js
https://eaflood.atlassian.net/browse/WATER-4740
This request has come from the [http://github.com/DEFRA/water-abstraction-team](Water Abstraction Team) to amend the transaction file generated for SROC bill runs.
When the transaction is flagged as being two-part tariff, we currently have logic that outputs an attempt to explain how the charge was calculated. However, if the charge involves aggregates, the explanation is wrong. Explaining the charge in a short sentence would be a project itself! So, they have requested we drop the output altogether and leave it blank.
> Stop populating col35 in SROC 2PT transaction file

- .github/workflows/ci.yml
- .labrc.js
The SonarCloud CI action is deprecated in favour of SonarQube; we therefore amend our `ci.yml` to use the SonarQube action.
> Update CI to for SonarQube
