DEFRA/sroc-charging-module-api

- app/auth/jwt_strategy.auth.js
- app/controllers/regimes.controller.js
Sonarcloud has some code smells we can resolve before we move on with the project.
This change resolves what we can now.
> Fix some sonarcloud code smells

- app/presenters/charge.presenter.js
- app/presenters/index.js
This change implements the final presenter needed for the calculate charge request, which is the one that presents the completed Charge object to the user.
> Create charge to user presenter

- db/seeds/01_regimes.js
- db/seeds/02_authorised_systems.js
This is the pattern we now use in our code rather than direct Promises. So should make it a little easier to understand and more consistent with the rest of our other code.
> Update seed files to use async / await pattern

- app/models/authorised_system.model.js
- app/models/bill_run.model.js
- app/models/index.js
- app/models/regime.model.js
- db/migrations/20201127163958_create_bill_runs.js
Next step in being able to create a bill run is having a table in the db and a model to represent it in the code.
This change includes the code for both!
> Add bill run table and model

- app/services/create_bill_run.service.js
- app/services/index.js
- test/services/create_bill_run.service.test.js
This adds a new create bill run service ahead of adding a create bill run endpoint.
> Add create bill run service

- app/controllers/base_bill_runs.controller.js
- app/controllers/index.js
- app/controllers/presroc/bill_runs.controller.js
- app/routes/bill_run.routes.js
- test/controllers/presroc/bill_runs.controller.test.js
Now we have a proper bill run create service it's time to update our existing bill runs controllers to match how we expect them to operate.
At the moment we just have the create a bill run service. So this change updates the bill runs controllers to just support this functionality.
> Update bill runs ctrlr. to use new functionality

- Dockerfile
- docker-compose.yml
This implements a multi-stage docker build for `development` and `production`.
> Multi-stage docker build

- app/controllers/presroc/bill_runs.controller.js
- test/controllers/presroc/bill_runs.controller.test.js
- test/support/helpers/bill_run.helper.js
- test/support/helpers/index.js
https://trello.com/c/gTcQmR8M
This change links the bill run create transaction endpoint with the new `CreateTransactionService`.
> Link add transaction endpoint with service

- db/migrations/20210302125559_create_customers.js
https://trello.com/c/i7tD1V78/1922-m-change-customer-details-v2
The first stage of being able to change customer details is to create the `customers` table, which is what we do in this change with the following fields:
- `regime_id` (mandatory)
- `region` (mandatory)
- `customer_reference` (mandatory)
- `customer_name` (mandatory)
- `address_line_1` (mandatory)
- `address_line_2`
- `address_line_3`
- `address_line_4`
- `address_line_5`
- `address_line_6`
- `postcode`
> Create customers table

- .dockerignore
- app/services/generate_transaction_file.service.js
- app/services/index.js
- config/server.config.js
- package-lock.json
- package.json
- test/services/generate_transaction_file.service.test.js
https://trello.com/c/NfozGoQ6/1929-m-develop-generate-transaction-files-v2
The first stage is to create an initial `GenerateTransactionFileService` which can write a file to a temp folder. For now it just writes `Hello world!` to a given file; we will be changing it later to write actual transaction file data.
> Initial Generate Transaction File Service

- .env.example
- .labrc.js
- app/services/index.js
- app/services/send_file_to_s3.service.js
- config/index.js
- config/s3.config.js
- config/server.config.js
- package-lock.json
- package.json
- test/services/send_file_to_s3.service.test.js
https://trello.com/c/NfozGoQ6/1929-m-develop-generate-transaction-files-v2
The next stage of generating transaction files is to be able to upload files to an AWS S3 bucket. This service implements the `SendFileToS3Service` to do this. It will optionally upload files to a separate archive bucket, and optionally delete files after uploading.
The `@aws-sdk/client-s3` package exposes some global variables which cause unit tests to fail; to fix this we have to update `.labrc.js` to ignore them.
The service uses these new environment variables relating to temp file handling have been added (defaults are listed):
```
TMPDIR=/tmp/
REMOVE_TMP_FILES=true
```
(`TMPDIR` was actually added in a previous PR but wasn't added to `.env.example` at the time)
Environment variables relating to S3 access have …
> Send File To S3 service

- app/controllers/presroc/bill_runs_invoices.controller.js
- app/routes/bill_run_invoice.routes.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
https://trello.com/c/GVybPen8
The first step of developing Invoice Rebilling is to set up a stub endpoint, which is done in this change.
> Initial Invoice Rebilling endpoint

- app/controllers/admin/customers.controller.js
- app/routes/customer.routes.js
- test/controllers/admin/customers.controller.test.js
https://trello.com/c/h5nxl1FS/1949-s-develop-qa-customer-files-endpoint-v2
This sets up the initial show customer files endpoint.
> Admin customer changes dummy endpoint

- app/translators/customer.translator.js
- test/translators/customer.translator.test.js
https://trello.com/c/gRWL23rB
When we added the [Customer Details service](https://github.com/DEFRA/sroc-charging-module-api/pull/262) we also added a translator with some validations. However, our BA who is more on the ball than us spotted that there were some validations missing.
This change fixes that issue by adding the midding validations.
> Fix missing customer validations

- app/services/index.js
- app/services/invoice_rebilling_create_licence.service.js
- test/services/invoice_rebilling_create_licence.service.test.js
https://trello.com/c/qkWbpJlf/1962-m-create-re-billing-transactions
In order to create a transaction and update the tallies we first need to create a licence. This simple `InvoiceRebillingCreateLicenceService` will do this.
> Create Invoice Rebilling Create Licence Service

- app/controllers/presroc/bill_runs_invoices.controller.js
- test/controllers/presroc/bill_runs_invoices.controller.test.js
https://trello.com/c/GVybPen8/1945-m-receive-respond-to-re-billing-request
The last part of creating a working rebilling endpoint is to update `BillRunsInvoicesController.rebill` to use our rebilling services to validate the request then initiate the the rebilling process.
> Update Invoice Rebilling Controller

- app/routes/bill_run_invoice.routes.js
https://trello.com/c/GVybPen8
The rebilling functionality has now been fully tested and signed off by the team. As such we are ready to make it available in all environments.
> Enable rebilling

- app/tasks/task_runner.js
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-68
The final step of setting up an automated task is to add the task to the switch statement in `TaskRunner`.
> Add `DataExportTask` to `TaskRunner`

- app/services/bill_runs/view_bill_run.service.js
- app/services/files/exports/export_data_files.service.js
- app/services/invoices/invoice_rebilling_create_transaction.service.js
- app/services/invoices/invoice_rebilling_validation.service.js
- app/services/invoices/view_invoice.service.js
- app/services/transactions/create_transaction.service.js
[Moving services into folders](https://github.com/DEFRA/sroc-charging-module-api/pull/514) caused SonarCloud to re-review all our services, resulting in a number of errors being raised. This PR is to review and handle each one -- either fixing them or marking them as "will not fix", as appropriate.
> CMEA-102: SonarCloud fixes

- app/services/readme.md
https://eaflood.atlassian.net/jira/software/projects/CMEA/boards/907?selectedIssue=CMEA-102
After organising our services, we document how we've organised them for future reference.
> Document services folder

- test/controllers/bill_runs.controller.test.js
- test/controllers/bill_runs_invoices.controller.test.js
- test/controllers/bill_runs_licences.controller.test.js
- test/controllers/bill_runs_transactions.controller.test.js
- test/controllers/calculate_charge.controller.test.js
- test/controllers/customer_details.controller.test.js
- test/controllers/customer_files.controller.test.js
[https://github.com/DEFRA/sroc-charging-module-api/pull/513](We previously moved the controllers out of the `presroc` folder) but forgot to move the tests to match -- we therefore fix this here.
> Move controller tests out of `presroc` folder
